### ISSUE TITLE
DDF - DIF analýza pro distraktory

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#10]
Přidat distractor plot pro skupiny

**Comment by patriciamar** [comment]
Nebo jinou analyzu DDF, napr. pomoci multinomicke regrese.

**Comment by drabinova** [comment]
funkce ddfMLR v difNLR balicku (v 1.0.0.)

**Comment by patriciamar** [comment]
Perfektní!

**Comment by drabinova** [comment]
Byla přidána záložka DDF do DIF/Fairness. Je zde výstup z ddfMLR() funkce, graf a tabulka parametrů. Je nutné přidat popisky, citace, rovnice a interpretaci. Také je potřeba dodat SD odhady.

**Comment by drabinova** [comment]
SE přidáno. Mělo by být vše OK. Po kontrole prosím uzavřít

**Comment by drabinova** [comment]
Můžeme tedy uzavřít? Nebo je potřeba ještě něco dodat?

**Comment by patriciamar** [comment]
Vypadá to dobře.
