### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#107]
Abychom věděli, jak uživatelé aplikaci využívají.

**Comment by drabinova** [comment]
Tady je návod
https://shiny.rstudio.com/articles/google-analytics.html

**Comment by patriciamar** [comment]
TOto by bylo slvělé už do příští verze!

**Comment by patriciamar** [comment]
Zdá se, že je funkční, prozatím uzavírám.
