### ISSUE TITLE
Testování dat

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#109]
Pokud uživatel nenahraje 'group' aplikace poběží normálně, ale v DIF/Fairness sekci jsou vypsány pouze errory jednotlivých funkcí. Momentálně je v sekci Data upozornění na to, že analýza v DIF/Fairness nepoběží, ale errors nejsou nijak ošetřené. Zvážit přidání příkazu validate()
viz https://shiny.rstudio.com/articles/validation.html

**Comment by drabinova** [comment]
Je potřeba vyzkoušet, zda aplikace nespadne, když uživatel vloží špatná data (př. jiný počet sloupců než je délka klíče atd.)

**Comment by drabinova** [comment]
Asi hotovo, po kontrole prosím uzavřít

**Comment by patriciamar** [comment]
Pro data GMAT2 vsechny metody DIF/DDF hlasi Error: Length of group is not the same as number of observation in the main data set!

**Comment by patriciamar** [comment]
Ani pro data difMedical20 a Medical100, zadna z DIF/DDF metod na serveru nefunguji. Bude nejspis potreba pridat do group header... Bud primo v Shiny nebo v danych baliccich.

**Comment by patriciamar** [comment]
Zda se, ze nefunguji ani Summary pro data Medical100.
Summary pro data Medical20 vypada divne, maximum je 10.

**Comment by drabinova** [comment]
Vypadá to, že se nenahrává správný key a group a stále zde zůstávají data pro GMAT, podívám se na to a zkusím opravit

**Comment by patriciamar** [comment]
Nejnovejsi verze je nyni na testovani pod odkazem Test4. Na https://shiny.cs.cas.cz/ShinyItemAnalysis/ je verze ze 16.1.

**Comment by patriciamar** [comment]
Mockrat diky!

**Comment by drabinova** [comment]
Teď už by to snad mělo fungovat

**Comment by drabinova** [comment]
Kontrolovala jsem (nechala jsem si navíc vypisovat group) datasety a vypadá to, že se nahrávají a přiřazují dobře. Pokud máte odzkoušeno a nemáte nikdo nějaký problém, asi můžeme také uzavřít?

**Comment by patriciamar** [comment]
Prozatim uzaviram, pokud by se opet vyskytly potize, znovuotevreme...
