### ISSUE TITLE
IRT models

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#112]
Možná bychom měli zvážit přidání 
- statistik na porovnání modelů (BIC, AIC, anova)
- model fit, item/person fit, 
- možnost exportu factor scores (odhady znalostí, graf zcela dole). 

Factor scores zaberou hodně času a asi by se první stránka dost zrychlila, kdyby byly počítány až po rozkliknutí nějaké option.

**Comment by drabinova** [comment]
Přikládám možnou úpravu pomocí `mirt` balíčku, která celou záložku IRT models výrazně zrychlí.  `mirt` poskytuje podobné obrázky jako `ltm`, navíc má však dobře naprogramované (rychlé a obecné) funkce k vyhodnocení modelů atd. - viz zdroják

`library(difNLR)`
`library(mirt)`
`data(GMAT)`
`data <- GMAT[, 1:20]`


`### IRT models`
`###### Rasch model model = 1, itemtype = "Rasch", constrain = NULL`
`###### 1PL with the fixed discrimination`
`###### model <- 'F = 1-20`
`######           CONSTRAIN = (1-20, a1)'`
`###### nebo`
`###### model = 1, itemtype = "2PL", constrain = list((1:ncol(data)) + seq(0, (ncol(data) - 1)*3, 3))`
`###### 2PL model = 1, itemtype = "2PL", constrain = NULL`
`###### 3PL model = 1, itemtype = "3PL", constrain = NULL`
`fitR <- mirt(data, model, itemtype = itemtype, constrain = constrain)`

`# COEF`
`coef(fitR)`

`# PLOTS`
`# expected total score`
`plot(fitR, type = "score")`

`# test information function`
`plot(fitR, type = "info")`

`# reliability`
`plot(fitR, type = "rxx")`

`# test standard errors`
`plot(fitR, type = "SE")`

`# item trace lines - characteristic curves multiple figure`
`plot(fitR, type = "trace")`
`plot(fitR, type = "trace", facet_items = F)`

`# item information trace lines - multiple figure`
`plot(fitR, type = "infotrace")`
`plot(fitR, type = "infotrace", facet_items = F)`

`# expected item scoring function - multiple figure`
`plot(fitR, type = "itemscore")`
`plot(fitR, type = "itemscore", facet_items = F)`

`# test information and standard errors - combination`
`plot(fitR, type = "infoSE")`

`# factor scores`
`fs <- fscores(fitR)`
`sts <- as.vector(scale(apply(data, 1, sum)))`

`df  <- data.frame(fs, sts)`

`ggplot(df, aes_string("sts", "fs")) +`
    `geom_point(size = 3) +`
`    labs(x = "Standardized total score", y = "Factor score") +`
 `   theme_bw() +`
  `  theme(text = element_text(size = 14),`
   `       plot.title = element_text(face = "bold", vjust = 1.5),`
    `      axis.line  = element_line(colour = "black"),`
     `     panel.grid.major = element_blank(),`
      `    panel.grid.minor = element_blank(),`
       `   panel.background = element_blank()) +`
    `theme(legend.box.just = "left",`
     `     legend.justification = c(1, 0),`
      `    legend.position = c(1, 0),`
       `   legend.box = "vertical",`
        `  legend.key.size = unit(1, "lines"),`
         ` legend.text.align = 0,`
          `legend.title.align = 0)`


`### comparing two models`
`fit1 <- mirt(data, 1, "Rasch")`
`fit2 <- mirt(data, 1, "2PL")`
`anova(fit1, fit2)`


`### person fit`
`personfit(fitR)`

`

**Comment by patriciamar** [comment]
mirt vypada velmi dobre! Bylo by mozne vytvorit jej zatim jako samostatny list?

**Comment by drabinova** [comment]
- mirt přidán jako samostatný list
- models comparison přidáno jako další záložka v IRT models

Co je ještě potřeba?

**Comment by patriciamar** [comment]
mirt vypada pekne.

Zatim nam zlobi pridani baliku mirt na Shiny server. Nejake napady? Hlasi to toto:

* installing *source* package ‘RcppArmadillo’ ...
** package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -m64 accepts -g... yes
checking how to run the C++ preprocessor... g++ -m64 -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ -m64 accepts -g... (cached) yes
checking whether g++ version is sufficient... no
configure: WARNING: Only g++ version 4.6 or greater can be used with RcppArmadillo.
configure: error: Please use a different compiler.
ERROR: configuration failed for package ‘RcppArmadillo’
* removing ‘/usr/lib64/R/library/RcppArmadillo’
ERROR: dependency ‘RcppArmadillo’ is not available for package ‘mirt’

Kompiler prý nemá update.

**Comment by drabinova** [comment]
U mě to funguje bez problémů, [zde](http://stackoverflow.com/questions/13673183/cannot-compile-rcpparmadillo-in-r) radí spustit R v režimu `R --vanilla` a pak až nainstalovat balíčky.

Teď jsem ještě našla debatu vývojářů přímo na [GitHubu](https://github.com/RcppCore/RcppArmadillo/issues/97). Snad to pomůže!

**Comment by patriciamar** [comment]
Jakube, pan Marsik píše:

v /opt/shared/R-dif.tgz máte rozdíl oproti slonu
Instalace R
R packages.instal("shinny")
---------------------------
R packages.install("mitr")
---------------------------

Jak z toho udělat binární balíčky?

**Comment by drabinova** [comment]
To bude nějaký překlep, ne? 
jedná se o balíčky `shiny` a ne `shinny` a `mirt` a ne `mitr`

**Comment by drabinova** [comment]
Možno uzavřít?
