### ISSUE TITLE
R package

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#121]
Odstranila jsem momentálně balíčky `foreign`, `gridExtra` a `shinyAce` z dependencies, jelikož to vypadá, že nejsou vůbec potřeba. Balíček jsem následně zkompilovala bez problémů. Pokud by u vás nastal nějaký problém, dejte mi vědět.

**Comment by patriciamar** [comment]
Ceka mj. jeste na kontrolu dokumentace k novym datum

**Comment by drabinova** [comment]
Ok, zatím jsou kompilace balíčku bez problémů. Dneska jste se ještě bavili i `latticeExtra`, je jej nutné přidat?

**Comment by patriciamar** [comment]
Prosim pridat vsechny nove pridane balicky do dependencies.

**Comment by drabinova** [comment]
Hotovo, zmenila jsem prikaz library(package) na require(package), coz by melo vyhodit ERROR pokud balicek neni stazen a aspon budeme vedet, na ktery jsme pripadne zapomneli. Chod aplikace by to (snad) nemelo ovlivnit

**Comment by drabinova** [comment]
Pridala jsem shinyjs i do ui.R, kde se volala funkce useShinyjs. Ted uz by to melo byt v poradku. Pripadne chyby hlaste, zkusim opravit

**Comment by patriciamar** [comment]
Skvele, zda se, ze vse funguje. Nejnovejsi verze na Test20170124 uz bezi, lze testovat.

**Comment by drabinova** [comment]
Uzaviram, vice v #154
