### ISSUE TITLE
IRT mirt - stahování obrázků

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#123]
Nefunguje momentálně stahování obrázků pro IRT mirt modely. Nejedná se o klasický plot a ani o ggplot.

**Comment by patriciamar** [comment]
Toto je dulezita soucast. Abychom mohli pripadne ponechat pouze zalozku IRT mirt, stahovani obrazku by melo fungovat.

**Comment by patriciamar** [comment]
Nyni jiz je na ostrem linku. Vse ozkouseno, nefunguji pouze downloady prvnich tri obrazku u Bockova modelu.

**Comment by drabinova** [comment]
Melo by byt jiz OK

**Comment by drabinova** [comment]
Po kontrole prosim uzavrit, u me funguje

**Comment by patriciamar** [comment]
Funguje, diky!
