### ISSUE TITLE
IRT mirt - fitovani 1PL v GMAT2 datech

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#131]
Nově je problém v datech GMAT 2 pri fitovani 1PL IRT pomoci mirt. Vsechny odhady a jsou nulove. Pritom ani pro Rasch ani pro 2PL nulove nejsou. Chyba vznikla v poslednich upravach, napr. na Test3, kde mame o neco malinko starsi verzi to fituje spravne.

**Comment by drabinova** [comment]
Tohle bude problém špatného klíče, po opravě nahrávání dat by to mělo fungovat

**Comment by drabinova** [comment]
Je tento problém už vyřešen? U mě se nic takového nevyskytuje

**Comment by patriciamar** [comment]
Chyba se zda yt jiz vyresena.
