### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#138]
Doplnit reference na jednotlive stranky i na stranku References, optimalne i s linky na dane publikace.

- Wright map
- 1PL, 2PL, 3PL models
- Ames & Penfield (item fit)
- Bock
- Zumbo (logistic DIF)
- ... aj.

**Comment by drabinova** [comment]
Pridano AIC, BIC, brzy poslu commit

**Comment by drabinova** [comment]
Chybi doplnit 1PL, 2PL, 3PL a Zumbo - ktere clanky maji byt citovany?

**Comment by patriciamar** [comment]
Reference budeme doplnovat postupne, pro tuto verzi bych to uz uzavrela...
