### ISSUE TITLE
Zdrojový kód

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#14]
Vypsat vybraný zdrojový kód k jednotlivým sekcím

**Comment by patriciamar** [comment]
Vypada to pene. Bude dulezite, aby slo vyuzit predpripravene funce, napr. distractors plot.

**Comment by drabinova** [comment]
Efektivnejsi psani

**Comment by drabinova** [comment]
Přidáno, prosím o kontrolu

**Comment by patriciamar** [comment]
Vypada to moc pekne. Prosim o par uprav:
Vsude nadpis "Selected R code" (nekde je drobny preklep, nekde chybi).
Na zvazenou: Uvodni kod (prvni ctyri radky, nacitani datasetu, v zalozce multinomial prvnich 9 radku) bych nechala jenom na prvni strane summary. Nacteni skupiny jen u DIF v zalozce summary. Plus: zkrati se to, Minus: kdyz si nekdo nakopiruje jen jeden list, nemusi mu to fungovat.

**Comment by drabinova** [comment]
Upraveno, kod zatim nemenen. Mozna bude lepsi pockat na reakce po workshopu
