### ISSUE TITLE
Bold rows in datatable()

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#144]
Last three rows in `regr_comp_table` are needed.

**Comment by patriciamar** [comment]
Is it possible to force the colnames to allign with appropriate collumns?

**Comment by drabinova** [comment]
As I said here #124 it is not problem of our table, it is problem of chrome and I do not think we can do anything about it

**Comment by patriciamar** [comment]
Maybe someone will have an idea :)
Interesting that resizing the window fixes the problem.

**Comment by drabinova** [comment]
This will be fixed in next commit.

**Comment by drabinova** [comment]
Please, review and close
