### ISSUE TITLE
data LF

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#15]
Přidat LF data s 80 položkami

**Comment by patriciamar** [comment]
Pridat 100 polozkova data chemie
- do balicku ShinyItemAnalysis jako chemistryABC() chemistryKEY)
- do Shiny aplikace jako jeden z moznych datasetu

**Comment by patriciamar** [comment]
Data pridana. Ceka se na pridani provizorniho balicku a bude to testovatelne i na webu v Testu.
zbyva
- pridat popisek na web (rozdelit popisek na Medical 100 a Medical 20 dif)
- zkontrolovat popisy funkci/dat v balicku, mozna bych zde jeste v budoucnu vylepsila volbu polozek dle toho, co jsme prezentovali na workshopu
