### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#154]
There is a problem with dependencies of dependencies when installing package from GH.
`library(devtools)`
`devtools::install_github("patriciamar/ShinyItemAnalysis", force = T)`

This does not install dependencies of dependencies. I don't really know how to force it to do that. I think it is a general problem when installing from GH, see hadley/devtools#1298 or YosefLab/scone#60. 

I don't have any problem with installation of old version from CRAN so I hope it will work with new version as well. We can recommend in README file to install firts from CRAN to install or dependencies. But this does not solve the problem in a good way.

Moreover, (I think) there is no possibility to install dependencies (or dependecies of dependencies) when using source package on your pc:
`install.packages("ShinyItemAnalysis_1.1.0.tar.gz", repos = NULL, type = "source")`

So if you had any suggestions what to do, I would be glad to hear them!

**Comment by drabinova** [comment]
I added packages `gridExtra` and `latticeExtra` into dependencies, list in ui file and into list in server file. They should be on server.

**Comment by consuelapaloeng** [comment]
Hi all,

I have the same problem.

library(devtools)
install_github("vqv/ggbiplot")

* installing *source* package 'ggbiplot' ...
** R
** data
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'munsell'
Error : package 'ggplot2' could not be loaded
ERROR: lazy loading failed for package 'ggbiplot'
* removing 'C:/Users/User/Documents/R/win-library/3.3/ggbiplot'
Error: Command failed (1)

Can someone help me.

Thanks

**Comment by patriciamar** [comment]
We don't have a solution to this problem yet and we will be happy to hear solution if someone has one. For now and for package ShinyItemAnalysis, we recommend downloading from CRAN.
