### ISSUE TITLE
mirt parametrization

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#156]
mirt uses different parametrization than ltm does. Is there an elegant way to switch to ltm parametrization when using mirt?

Different parametrization used in mirt and ltm will need to be considered when reporting item parameters (in the app as well as in the pdf/html report). For IRT models fitted with mirt this means either changing the reported model or changing the reported parameter estimates.

**Comment by patriciamar** [comment]
Solution seems to be here: https://philchalmers.github.io/mirt/html/ltm_models_with_mirt.html

**Comment by patriciamar** [comment]
As written [here](https://groups.google.com/forum/#!topic/mirt-package/5q5INhh0NGs), one can pass the option IRTpars = TRUE to the coef() function, and the traditional IRT metric will be returned...

**Comment by patriciamar** [comment]
Not sure how to enforce the method to print SE.

used:
fit3PLmirt <- mirt (data, model = 1, itemtype = "3PL", SE=TRUE)
coef(fit3PLmirt, simplify=T, IRTpars = TRUE, printSE=TRUE)

However, the SEs are not printed...

**Comment by drabinova** [comment]
Well, I asked Phil Chalmers about it, so we have to wait now, see philchalmers/mirt#99

**Comment by drabinova** [comment]
[Here](https://groups.google.com/forum/#!searchin/mirt-package/delta$20method%7Csort:relevance/mirt-package/qlHrupGOl2A/p9f_3y3SBQAJ) is the solution with delta method as we discussed before..

**Comment by drabinova** [comment]
Fixed. Please control and close

**Comment by patriciamar** [comment]
Looks great!
