### ISSUE TITLE
download button for correlation plot

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#158]
I'm not able to make DB for correlation plot work. Could anybody help?

**Comment by patriciamar** [comment]
Je to zvlastni, ale na serveru mi to nefunguje. Dala jsem to na ostrou verzi. Je to ozkousene na Testu?

**Comment by patriciamar** [comment]
Jakoby slo o starsi verzi, jeste to zkontroluju.
