### ISSUE TITLE
Bockův model

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#16]
Přidat do sekce DIF/Fairness Bockův model

**Comment by patriciamar** [comment]
Bockův model do sekce IRT models.

**Comment by patriciamar** [comment]
Muj stary kod (20.2.15):
# Nominal response model (NRM)            #
# and Nested logit model (2PLNRM, 3PLNRM) #

# neelegantni prepocet
for (i in 1:680)
  dataNRM<-rbind(dataNRM,as.numeric(data[i,varsA]))
keyNRM <- c(4,2,1,4,2,3,3,3,4,1,1,4,1,1,3,1,3,3,3,4)

# modely
mod1 <- mirt(dataNRM, 1, 'nominal')
mod2 <- mirt(dataNRM, 1, '2PLNRM', key=keyNRM)
mod3 <- mirt(dataNRM, 1, '3PLNRM', key=keyNRM)

**Comment by drabinova** [comment]
Můj nový kód. Vypadá to, že `2PLNRM` je to, co hledáme

`library(difNLR)`
`library(mirt)`
`data("GMATtest", "GMATkey")`
`data <- GMATtest[, 1:20]`
`head(data)`

`data <- sapply(1:ncol(data), function(i) as.numeric(data[, i]))`
`head(data)`
`colnames(data) <- paste("Item", 1:ncol(data))`
`key <- as.numeric(as.factor(GMATkey))`

`# NOMINAL MODEL`
`fitNOM <- mirt(data, 1, "nominal")`
`coef(fitNOM)`
`itemplot(fitNOM, 3)`

`# 2PLNRM`
`fit2PLNRM <- mirt(data, 1, "2PLNRM", key = key)`
`coef(fit2PLNRM)`
`itemplot(fit2PLNRM, 3)`

**Comment by drabinova** [comment]
Tady je další kód, kdy ostatní položky jsou odhadovány pomocí `2PL` modelu:

`library(difNLR)`
`library(mirt)`
`data("GMATtest", "GMATkey")`
`key <- as.numeric(as.factor(GMATkey))`
`data <- sapply(1:20, function(i) as.numeric(GMATtest[, i]))`
`colnames(data) <- paste("Item", 1:ncol(data))`
`scoredGMAT <- key2binary(data, key)`

`# 2PL IRT model for scored data`
`mod0 <- mirt(scoredGMAT, 1)`
`# nominal model for item 1 for unscored data`
`i <- 1`
`itemtype <- rep("2PL", ncol(data))`
`itemtype[i] <- "nominal"`
`df <- scoredGMAT`
`df[, i] <- data[, 1]`
`head(df)`

`mod1 <- mirt(df, 1, itemtype = itemtype)`

`# plots of characteristic curves for item 1`
`itemplot(mod0, 1)`
`itemplot(mod1, 1)`

**Comment by patriciamar** [comment]
Díky za update! Zatím úplně nerozumím, proč se ta interpretace theta takto změní, když se fituje nominal pro všechny položky... Připadá mi to jako bug v mirtu(?) Budu se těšit na update.

**Comment by drabinova** [comment]
Přidáno s omezením

**Comment by patriciamar** [comment]
Jeste nam sem pridam odkaz na diskusi k tomuto tematu, at ji tu mame: http://stackoverflow.com/questions/41671318/mirt-odd-results-for-nominal-model/41753852#41753852

**Comment by patriciamar** [comment]
Vypada to skvele, parada!
Jeste myslim, ze tady by uz stalo za to udelat zalozku Item, a vyobrazovat ICC pro polozky postupne. Nebo jen pridat pod graf ICC graf se sliderem, kde se budou vyobrazovat ICC polozek postupne.

**Comment by patriciamar** [comment]
Lze jiz prohlizet a testovat na https://shiny.cs.cas.cz/ShinyItemAnalysis/

**Comment by drabinova** [comment]
Záložky pro IRT (nebo jen Bockův model) bych asi nechala až do další verze. Předpokládám, že se budeme pokoušet řešit DDF pomocí Bockova modelu a bude jednodušší to implementovat najednou.

**Comment by patriciamar** [comment]
Dobrá, ponechme tedy prozatím, jak je, grafy pro položky (záložku Items) pořešíme v příští verzi.

Zatím prosím Jakuba o zprovoznění stahování obrázků i v této záložce (IRT models with mirt/Bock's nominal model).
