### ISSUE TITLE
Lokální verze

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#164]
Funguje vám aplikace lokálně? Po posledním updatu mi přestala fungovat. Nespadne, ale žádná analýza neproběhne (tj. žádné tabulky/ploty se mi nezobrazují, ani data)

**Comment by JakHou** [comment]
Před commitem mi vše lokálně fungovalo. Teď nefunguje ani lokálně

**Comment by JakHou** [comment]
zdá se, že update, který jsem udělal dnes okolo jedenácté proběhl špatně. asi se updatovalo dle nějaké "staré" verze. 

https://github.com/JakHou/ShinyItemAnalysis/commit/ddf3e77ccf7b93740eb2b970ecacde79495423a8
