### ISSUE TITLE
mirt package

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#17]
Zkusit využívat mirt package pro IRT modely

**Comment by patriciamar** [comment]
Muj stary kod:
# 2PL
mod0 <- mirt(data[,varsQR], 1) # 2PL model for binary data
summary(mod0) # FA parametrization
coef(mod0) # Explore the relationship between slope/intercept and loading
itemplot(mod0, 1) #a1 discrimination, d easiness
coef(mod0)$Item.2
itemplot(mod0, 2)

**Comment by drabinova** [comment]
Uzavírám, mluví se o tom v issue 112
