### ISSUE TITLE
IRT training ICC figures

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#172]
I think - for educational purposes - it would be great to have some training figures for IRT models where user can choose discrimination, difficulty and guessing and see how ICC would change.

**Comment by patriciamar** [comment]
Great idea! We could also user let the user to construct parameters of an entire item bank this way (more ICCs in one plot). After that we may let the user simulate the data from such a model.

**Comment by drabinova** [comment]
Training plots were added into IRT models section.

**Comment by patriciamar** [comment]
Great!

**Comment by patriciamar** [comment]
Jeste lze zvazit pridani informacni funkce polozky.

**Comment by drabinova** [comment]
Hotovo, po kontrole prosim uzavrit.
