### ISSUE TITLE
Online PDF file generation

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#174]
We will need to solve the issue with generation of the pdf file in online version at https://shiny.cs.cas.cz/ShinyItemAnalysis/

Often, it gives error message 502 Proxy Error, sometimes it generates the pdf file later, sometimes it does not. It seems mostly to depend on the time of the analysis.

**Comment by patriciamar** [comment]
Zkusit rozdeleni generovani a stahovani reportu.
Pridat doporuceni, aby uzivatel nejprve projel jednotlive analyzy online.

**Comment by patriciamar** [comment]
K vyzkoušení nejnovější verze na TestAD. Zdá se, že funguje, občas vytuhne při delším zadání (Medical, 3PL, DIF multinomial)

K opravě:
- stránka Reports: DIF Method selection změnit na checkbox, první "Histograms by group only"
- IRT Model opravit (Wright map zarovnat, ICC přidat, vpravo, Parameter Estimates na novou stranku?)
- DIF/Fairness na novou stranku?

Zvážit 
- přidání grafu validity pro Total score (za correlation structure)
- do tabulky Traditional item analysis sloupec criterion, kam by přišla korelace item-criterion
(pozn. podobně jako RIT je korelace mezi item a total, toto by byla RIC - item criterion)

**Comment by drabinova** [comment]
Opravila jsem IRT modely a udělala jsem mezeru před DIF sekcí, změny pošlu zítra.

**Comment by patriciamar** [comment]
ICC jeste chybi v html

**Comment by drabinova** [comment]
Uz jsem to opravila, v pristi verzi to bude ok.

Zbyva tedy udelat checkbox. S tim pridavanim validity do reportu bych asi pockala do dalsi verze az to bude opravdu radne vyzkouseno.

**Comment by drabinova** [comment]
Checkbox hotov. Momentalne zbyva doresit Generate report vs Download report

**Comment by drabinova** [comment]
Tohle je možné asi taky uzavřít?

**Comment by patriciamar** [comment]
Zbyva pridani message boxu pro download.

**Comment by LStepanek** [comment]
Message box pro download reportu přidán mým posledním commitem.
