### ISSUE TITLE
Názvy položek

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#177]
V některých analýzách se položky přejmenují na Item 1, 2,... (např. Difficulty/Distractor Plot, všechny obrázky po položkách), v některých ale původní názvy zůstanou zachované (např. souhrnné výstupy z DIF analýz). Bude potřeba to sjednotit, domluvíme se, jak.

**Comment by drabinova** [comment]
Opraveno, pouze pro Delta plot nefunguje, protoze tam jsou polozky prejmenovany primo ve funkci, kterou pouzivame. To same pro difNLR package - tam to upravim a bude to fungovat v pristi verzi. Grafy funguji vside spravne.

**Comment by drabinova** [comment]
Po kontrole prosim uzavrit

**Comment by drabinova** [comment]
Fixed
