### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#19]
Když běží shiny objevují se občas při vykreslování tabulek a grafů errory, které ovšem nevedou k spadnutí aplikace. Asi by ale bylo dobré jednotlivě je projít a pokud možno odstranit.

**Comment by patriciamar** [comment]
Traditional Analysis/Distractors graf dole hlasi Error: replacement has 0 rows, data has 4

**Comment by patriciamar** [comment]
Logistic regression on Standardized Total Score:
tabulka Table of parameters hlasi chybu: object 'x2' not found

**Comment by drabinova** [comment]
Warning in min(table(isolate(sliderUpdate$entryValues))) :
  no non-missing arguments to min; returning Inf
line cca 230, nejspis ten nekonecny cyklus pro slidery

**Comment by drabinova** [comment]
Error in if: argument is of length zero
Nejspis line 309, podle me tento a predchozi souvisi se slidery

**Comment by drabinova** [comment]
Warning: Error in [[: attempt to select less than one element
okolo line 516, pravdepodne davame list[[0]], v te oblasti pouzivame pouze slidery, takze pravdepodobne se to vyresi samo

**Comment by JakHou** [comment]
Upravil jsem ty slidery, mělo by to již být vyřešeno. Poprosil bych však o otestování, abych mohl případné nedostatky odstranit

**Comment by drabinova** [comment]
Ok, jdu to sloučit a odzkoušet

**Comment by patriciamar** [comment]
Slidery zdá se fungují, prosím ještě o kontrolu / opravu tlačítka Play.

**Comment by patriciamar** [comment]
DIF logistic IRT Z Table hlasi Error object x2 not found

**Comment by patriciamar** [comment]
IRT Raju Items hlásí 2x Error substrát out of bounds.

**Comment by drabinova** [comment]
Warning in (function (..., list = character(), package = NULL, lib.loc = NULL,  :
  data set ‘key’ not found
Warning in (function (..., list = character(), package = NULL, lib.loc = NULL,  :
  data set ‘test’ not found

**Comment by drabinova** [comment]
V aktuální verzi nejspíš ještě není vyřešeno?

**Comment by drabinova** [comment]
Pri spusteni dostavam nasledujici error:
Warning in validateSelected(selected, choices, inputId) :
  'selected' must be the values instead of names of 'choices' for the input 'dataSelect'

Pouze esteticka zalezitost?

**Comment by drabinova** [comment]
V Traditional analysis/Distractors dostavam error:
ERROR: [on_request_read] connection reset by peer

**Comment by drabinova** [comment]
V Regression/Multinomial se tisknou iterace odhadovaciho algoritmu. Nejspis by se melo vypnout.

**Comment by drabinova** [comment]
IRT warning (souvisi s novou verzi ggplot2):
Warning: `legend.margin` must be specified using `margin()`. For the old behavior use legend.spacing

**Comment by patriciamar** [comment]
Zlobi nacitani dat s jinym poctem polozek. (aplikace vytuhne)

Warning: Error in score: Number of items is not equal to the length of key.

**Comment by drabinova** [comment]
Tady je možnost jak se elegantně vyhnout podivným errors, které mohou mást uživatele:
https://shiny.rstudio.com/articles/sanitize-errors.html

**Comment by drabinova** [comment]
v Items slideru je stupnice 1-3-5-7-9-12 atd., tedy mezi 9 a 12 jsou dvě čísla místo jednoho. Slider pak úplně přesně neodpovídá stupnici, např. pro 12 je spíš těsně za 12 atd. Navíc mezi ostatními čísly jsou dvě čárky, přitom je tam ale jen jedna hodnota (krom teda 9-12)

**Comment by JakHou** [comment]
Načítání dat
Problém spočívá v tom, že zatím je nahrávání vlastních dat koncipováno následovně:
1. uživatel nahraje svá data
2. skript tato data zpracuje spolu s klíčem a snaží se spočítat skóre a všechny příslušné věci

Faktem je, že v shiny zůstane starý klíč, který má jiný počet odpovědí nebo dokonce jiný formát. Proto se objeví chybová hláška, že počet položek není roven délce klíče

Toto by se dalo řešit několika způsoby: 
1. Překopání nahrávání dat tak, že se vytvoří jakýsi "submit button", kdy data nebudou nahrána do té doby, dokud si uživatel sám neřekne
2. Změnit vstupní data tak, že se bude nahrávat jeden velký soubor, který bude obsahovat vše potřebné 
3. Změnit koncept nahrávání tak, že v shiny aplikaci se nic nezmění, ale bude se muset razantně upravit skript pro nahrávání a ošetřit tak všechny možnosti a nesrovnalosti

**Comment by JakHou** [comment]
**Stupnice item sliderů**
Netuším, kde vzniká problém. Zjistil jsem, že pokud se mění hodnoty při inicializaci slideru, konkrétně max=10 na třeba max=20, tak se stupnice promění zase jiným způsobem, pokud na max=1, opět to vypadá jinak. 

Položil jsem dotaz na stackoverflow 
http://stackoverflow.com/questions/41568076/weird-behavior-of-shiny-sliderinput

**Comment by drabinova** [comment]
**Stupnice item sliderů**
Vypadá to tedy, že se jedná (snad) pouze o kosmetickou záležitost. Stačí, když si to budeme pamatovat a třeba se postupem času nějaké řešení naskytne.

**Načítání dat**
Co z těch možností je nejjednodušší? Já bych spojování datovým souborů moc nepreferovala, protože v takovém formátu jsou již obsaženy v balíčcích. Navíc by to zkomplikovalo vytváření pro uživatele. Osobně bych asi zvolila submit button, ale nemám představu, jak to je náročné na předělání.

**Comment by JakHou** [comment]
**Načítaní dat**
Jak to je v balíčcích by nemuselo vyvolávat potíže, ale je pravdou, že pro uživatele by vytváření vlastních dat mohlo být obtížné v tomto případě. Submit button by tak mohl být dobrou možností, která by nemusela být tak náročná. 

Byl bych také pro, aby se vytvořil submit. 

Pokud ale budou jiné nápady, tak se to může udělat ještě jinak, mě však napadly pouze tyto možnosti

**Comment by patriciamar** [comment]
Submit vypada pekne. Jeste prosim osetrit, aby aplikace nepadala, pokud data maji spatny format, ale aby nahlasila pripadne chybu. Momentalne mi nejnovejsi verze na desktopu pada pri nacteni a submittovani dat: HCI_ABCD, HCIkey. Pritom myslim, ze rozmery jsou spravne. Je to ale potreba otestovat i na spatnych datech (napr. zamenit vektor key s vektorem group atp.)

**Comment by drabinova** [comment]
Při pdf reportu na difMedical 20 datech mi hlásí následující warning:
Warning in FUN(X[[i]], ...) : NaNs produced

žádný problém ale ve výsledném pdf nevidím

**Comment by patriciamar** [comment]
Dnesni nejnovejsi verze mi lokalne i na serveru hlasi ERROR: could not find function "useShinyjs", jde o novou funkci, je nekde k dispozici?
Nova verze je take k nahledu na /ShinyItemAnalysisTest20170124/
Jeste jsem vyzadala pridani baliku WrightMap.

**Comment by drabinova** [comment]
Jedna se o funkci z balicku shinyjs. Po instalaci balicku by to melo bezet

**Comment by patriciamar** [comment]
Diky! Bude potreba zkontrolovat, aby vsechny pouzite knihovny byly v seznamu Packages Used a take v dependencies balicku, aby si je automaticky tahal.

**Comment by patriciamar** [comment]
Na serveru je balík shinyjs nainstalován, ale Error přetrvává. Lokálně bylo potřeba balík také naloadovat pomocí library.

**Comment by patriciamar** [comment]
Pokud jiz nemame zadne Errors v teto verzi, myslim, ze bych toto Issue uzavrela a pripadne je budou postupne otvirat nove.

**Comment by drabinova** [comment]
Souhlasim
