### ISSUE TITLE
Message box with warning in reports

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#190]
Add message box when dowloading reports with warning - not to change settings and that it takes some time to dowload it

**Comment by drabinova** [comment]
It would be great to add progress bar (if it is possible) for reports, see https://shiny.rstudio.com/articles/progress.html

**Comment by LStepanek** [comment]
First version of warnings message box before report downloading was added. It pops up when a user clicks on "Generate Report" button.
