### ISSUE TITLE
Reports description

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#193]
Some description about reports would be useful - e.g. what is included by default.

**Comment by drabinova** [comment]
- what is included by default
- that setting is determined by options in app (e.g. when user apply correction method or purification during exploration of app this is then used in report; purification; type of plot for distractors; etc)

I would write these points below format option, above Correlation structure box.
I would also include some partition of report page - e.g. with header "Reports options" or so.

**Comment by drabinova** [comment]
Maybe bug - only one option in DIF model selection is allowed for reports.

**Comment by drabinova** [comment]
Add checkbox for DIF report selection

**Comment by drabinova** [comment]
Hotovo, po kontrole prosim uzavrit

**Comment by patriciamar** [comment]
Vypada to pekne. Do DIF method selection bych prvni volbu prejmenovala na "None - histograms by group only". Jinak lze uzavrit.

**Comment by drabinova** [comment]
Hotovo
