### ISSUE TITLE
DDF generovani plotu pro report

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#197]
Volba DIF multinomial v pdf reportu hlasi chybu
Error : object of type 'closure' is not subsettable

v online verzi hlasi 
ERROR: "legend.spacing.x" is not valid theme element name.

**Comment by drabinova** [comment]
Tohle je záležitost difNLR balíčku, Před nahráním jsem plotováné ddfMLR zkoušela a fungovalo mi. Zkusím na to kouknout v pondělí, ale je možné, že to souvisí s novou verzí ggplot2 balíčku, je na serveru nahraná nejnovější verze?

**Comment by drabinova** [comment]
Jeste zde byl maly preklep, ted by snad melo vse fungovat OK, pokud se nahraje vyssi verze `ggplot2`

**Comment by drabinova** [comment]
Po kontrole prosím uzavřít

**Comment by patriciamar** [comment]
Vyzkouseno i online.
