### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#208]
GA doporučuje filtrovat naše IP adresy, aby nenarušovaly statistiky. Stojí to za zvážení.

**Comment by drabinova** [comment]
GA podle mě momentálně nefunguje

**Comment by patriciamar** [comment]
Po posledni oprave zda se funguje. Po kontrole lze uzavrit.

**Comment by drabinova** [comment]
Prosím o kontrolu, zda fungují filtry. Mi se zdá, že ne

**Comment by patriciamar** [comment]
Prosim o pridani GA s cislem 5 pro https://rstudio.stat.washington.edu/shiny/ShinyItemAnalysis/

**Comment by drabinova** [comment]
Přidáno

**Comment by patriciamar** [comment]
Mockrat děkuji za přidání.
Z mé pracovní IP adresy zdá se filtr na ostré verzi funguje: web mne nezaznamenal, mobil ano.
