### ISSUE TITLE
Test dataMFF

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#211]
V traditional analysis hlasi
Error: unused argument (item.names = item_numbers())

stejny error se objevi pri generovani reportu.

**Comment by drabinova** [comment]
Offline se mi error nevyobrazuje. Argument item.names je napr ve funkci plotDistractorAnalysis(), takze pravdepodobne neni nekde nahrana spravna verze bud naseho balicku nebo funkci v adresari inst/shiny-examples/ShinyItemAnalysis.

Error nevidim ani online.

Reporty (html) mi s tim datasetem bezi jak online tak offline.

**Comment by patriciamar** [comment]
To je zvlastni, chybu se mi ted nedari replikovat. Prima, tedy funguje, uzaviram.
