### ISSUE TITLE
Analyzy validity

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#214]
Do casti validity bude potreba pridat:
- korelace s vysvetlujici promennou, scatterplot/boxplot
- distractors dle vysvetlujici promenne (ve 2-5 kategoriich), obdobne jako distractors dle celkoveho skore

Do casti Data bude potreba pridat moznost nacteni vysvetlujici promenne. Je potreba pocitat s tim, ze muze byt binarni (studuje/nestuduje) nebo spojita (prumerny prospech). Pro data Medical100 mame zatim k dispozici binarni, zkusime zajistit i spojitou.

**Comment by drabinova** [comment]
Prvni verze validity pridana. Po odzkouseni mozne rozsirovat.

**Comment by patriciamar** [comment]
Testuji na datech mff2016, vypada to moc pekne! Bez problemu bezi pro binarni, diskretni i spojitou promennou!

Mam tyto namety na upravy a rozsireni:
- promennou bych nazvala criterion variable (inspirace z funkce item.exam)
- do Traditional item analysis table bude mozne pridat dalsi sloupec tykajici se item.validity, bud pocitany jako korelace mezi polozkou a kriteriem, nebo pomoci item.exam (nebo oboji)
- Uvazuju, zda neposkytnout nejake p hodnoty i pro items (prip. i korigovane na mnohonasobna porovnani), but v tabulce v Item Analysis, nebo zopakovat korelaci polozky s kriteriem a p hodnotu primo u Validity distractor plotu.
- pro p>0 bych mozna zmenila "total score and predictive outcome are not correlated" na "we cannot coclude that a significant correlation exist"
- Bude prima nakonec pridat vzorovy kod

**Comment by drabinova** [comment]
Promennou prejmenuju a pro p>0 upravim text. Vzorovy kod jsem nevkladala, protoze zatim nemame pristupna data, pro ktera by to slo demonstrovat.

Ty korelace jsou obsazeny v Predictive validity, neni to zbytecne to uvadet znovu? Navic pridani nebude uplne trivialni, protoze ta promenna je optional a tedy se tam bude muset dat nejaka podminka, aby se tabulka tiskla i v pripade, ze tu promennou nemame.

Pokud budeme uvazovat korelace mezi polozkami a promennou, tam bych to radeji dala do Predictive validity/Items, at je ta analyza pohromade.

**Comment by drabinova** [comment]
Jeste jedna poznamka ke korelacim - momentalne pouzivat Pearsonuv korelacni koeficient, ale test zalozeny na nem predpoklada normalitu vektoru (X, Y). Asi bych tam pro jistotu dala jiny test - bud zalozeny na Kendallove tau nebo Spearmanove rho.

Je to doporuceno i v `?cor.test`

Pripadne je mozne tam dat vsechny tri testy a rict, ze Pearson se da pouzit jen v pripade, ze ta outcome vypada normalne.

**Comment by drabinova** [comment]
Toto by mělo být snad už vše hotovo, po kontrole prosím uzavřít

**Comment by patriciamar** [comment]
Moc pěkné, prozatím uzavírám.
