### ISSUE TITLE
Data Medical100 criterion

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#216]
Pridat kriterium pro data medical 100, zatim lze vyuzit binarni kriterium, ktere mame, bude prima pridat i spojite.

**Comment by drabinova** [comment]
Tohle se bude muset promyslet, protoze to rozbije cele cteni dat z balicku. Bude se to muset specialne osetrit. 

Jak by to pak fungovalo pro vice kriterii?

**Comment by patriciamar** [comment]
Asi by to zatim byly dva datesety. Probereme osobne.

**Comment by drabinova** [comment]
Hotovo, po kontrole prosim uzavrit

**Comment by patriciamar** [comment]
Pridano na Testu, vypada to moc pekne. 
Pro data Medical hlasi Predictive validity pod Number of groups Error: object 'cv' not found.

**Comment by drabinova** [comment]
Opraveno

**Comment by drabinova** [comment]
Na testu chybi ikony, ktere jsem pridavala. Jsou ve www adresari
