### ISSUE TITLE
DDF pro GMAT

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#228]
DIF/Fairness - DDF/Items pro GMAT vykresli pouze prvni polozku, pro dalsi hlasi Error: subscript out of bounds. Viz poslední verze na TestAD.
Prekvapive report se vygeneruje, vykresli polozku 1, 2, 9.

**Comment by drabinova** [comment]
Opraveno, pošlu v další verzi

**Comment by patriciamar** [comment]
nova verze je na Testu, funguje pekne.
