### ISSUE TITLE
"The application unexpectedly exited." when Medical 100 dataset is chosen

### ISSUE THREAD

**Issue by LStepanek** [patriciamar/ShinyItemAnalysis#236]
V nejaktuálnější verzi (po request merged #235) na serveru 1. LF (http://shiny.statest.cz:3838/ShinyItemAnalysis/) zlobí volba datasetu Medical 100. Buďto hned po loadování dat, nebo během jejich analýzy vrátí prohlížeč hlášku

'''
The application unexpectedly exited. Diagnostic information has been dumped to the JavaScript error console.
'''.

Verze mi nefunguje ani desktopově, vrací "Error: [.data.frame: undefined columns selected." opět u Medical 100 dat a konkrétně v záložce Item Analysis. Možná i jinde.

Jinak vypadá nová verze moc hezky.

**Comment by patriciamar** [comment]
Lubosi, bude potreba na vas server nahrat novy balicek ShinyItemAnalysis, jelikoz se uvnitr balicku zmenila data Medical, obsahuji nyni navic sloupec s uspesnosti ve studiu. Tva aplicace si momentalne taha starsi data, ze starsi verze balicku, kde ten sloupec chybi.

**Comment by LStepanek** [comment]
Patricie, děkuji, zařídím to.
