### ISSUE TITLE
paddings in mobile-web version

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#251]
Please add top-padding in mobile-web version.

**Comment by LStepanek** [comment]
I managed this within my last commit (#256).

**Comment by patriciamar** [comment]
jeste sem pridavam dalsi issues k mobile verzi:
- Test and item analysis presahuje do textu (zmineno v commitu)
- divne zobrazeni autoru

**Comment by drabinova** [comment]
Autori by v pristim komitu meli byt snad uz opraveni - dokoncuji verzi, za chvili poslu

**Comment by LStepanek** [comment]
Jo, autory jsem posledním commitem taky vyřešil -- už jsem poslal pull request, ale lze to vynechat. Stran zalamování textu "Test and item analysis" v headeru, to je otázka responzivního designu headeru. Podívám se na to, cca vím, jak na to (<row> tagy), ale je to o něco těžší než s těmi autory.

**Comment by drabinova** [comment]
No, ja ted nejsem schopna to synchronizovat. Asi mi to chvili zabere..

**Comment by drabinova** [comment]
Asi teď bude nutné přidat padding bottom pro web verzi

**Comment by drabinova** [comment]
Co se týče toho zalamování - už jsem se dívala, jestli by ten podnadpis nemohl být pod názvem, ale nepodařilo se mi to zprovoznit. Musela by se asi zvýšit výška navigační lišty. Ale možná to půjde vyřešit nějak jinak..

**Comment by LStepanek** [comment]
Zkusil jsem nastavit chování headeru pro všechny možné šířky obrazovek. Text "Test and item analysis" se už zalamuje v rámci headeru a nikdy není překryt žádný nadpis nebo text těla. Footer se dle mě chová správně -- buďto ho budeme chtít, aby byl scrollovací a bez odsazení od textu těla, nebo fixovaný s odsazením.

**Comment by drabinova** [comment]
Super, teď to vypadá dobře. Akorát u footeru se mi překrývá text, když si zmenším okno - na stránce About se mi objeví jen as published by Free Software... ale Foundation už je překryto footerem. Jde to nějak odsadit?

**Comment by LStepanek** [comment]
Ano, u toho footeru to vidím. To by snad neměl být problém, hned to zkusím upravit.

**Comment by LStepanek** [comment]
Řešení pro nepřekrývání footeru a textu v těle stránky přidáno posledním commitem (#267).

**Comment by drabinova** [comment]
Skvělé! Díky moc. Uzavírám

**Comment by LStepanek** [comment]
Ještě v posledních řádcích chunků kódů dochází k částečným překryvům. Trochu jsem to prázdné místo mezi footerem a textem rozšířil (#268).
