### ISSUE TITLE
DIF Logistic, Logistic Z - grafy polozek nezohlednuji korekci

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#252]
Zda se, ze grafy polozek nezohlednuji zvolenou korekci na mnohonasobna porovnani.
Testovano na datech HCI:
- bez korekce jsou DIFove 1, 12, 19, 20
- s korekci BH nejsou DIFove zadne
- Items vykresluje pri BH korekci polozky 1, 12, 19, 20 jako DIFove

Pozn.: diNLR reaguje spravne

**Comment by drabinova** [comment]
Tohle úplně bug není, je to napsáno v NOTE na jednotlivých stránkách: 
NOTE: Plots and tables are based on DIF logistic procedure without any correction method.

To je tím, že takový výsledek dává difR, resp. jeho funkce difLogistic(), a musel by to opravit David.

**Comment by patriciamar** [comment]
Diky! Myslim, ze uz jsme to kdysi resili.
Premyslim, zda by pak tedy nemela byt moznost volby Correction method ze stranek Items odstranena.

**Comment by drabinova** [comment]
Asi bych to nechala teď jak to je a případně se můžeme domluvit s Davidem, aby to opravil.
