### ISSUE TITLE
Reference list

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#253]
Prosim pridat k datasetu GMAT za posledni vetu napr. See Martinkova, Drabinova et al. for further discussion. Take prodim pridat na posledni stranku referenci uplnou citaci clanku DIF HCI. Na obou mistech s linkem vcetne supplementu www.lifescied.org/content/16/2/rm2.full.pdf+html?with-ds=yes

**Comment by drabinova** [comment]
Přidáno, pošlu s dalším commitem
