### ISSUE TITLE
Reports - add some text

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#283]
Some text/comments/interpretation should be added into reports.

**Comment by drabinova** [comment]
Is it know what text do we want to add?

**Comment by patriciamar** [comment]
As the first step, adding wording from the application as it appears above each figure/plot would be great.
However, consider also page layout, e.g. adding wording above DDplot will cause split of the table below the plot, even for GMAT data.
It seems to me very important to add the choice of adding own text, see #278

**Comment by drabinova** [comment]
For the first step see #305

**Comment by patriciamar** [comment]
Looks great! It is already available at https://shiny.cs.cas.cz/ShinyItemAnalysis/
Generalized DDplot #285 is also implemented, thus, to function properly, ShinyItemAnalysis version 1.2.1 has to be installed on server.
