### ISSUE TITLE
Reports - validity

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#284]
Validity section should be added into reports.

**Comment by drabinova** [comment]
Could you @JakHou look at it, please?

**Comment by patriciamar** [comment]
First version available at TestAD now, thanks! 
These changes are needed:

For the Reports section webpage:
- Title "Correlation structure selection" rename to "Validity"
- checkbox should be "Correlation structure" (remove "+ Screeplot")
- below should be another check-box "Predictive validity"

In the report:
- please move section title above the plot
- please adjust the plot size
- please add text from the application (adjusted text below) and add the correlation/p-value.

Predictive validity
[plot]
Correlation of criterion variable and total score
Test for association between total score and criterion variable is based on Spearman`s ρρ. This rank-based measure has been recommended if data do not come from bivariate normal distribution. The null hypothesis is that correlation is 0.

**Comment by patriciamar** [comment]
It seems generation of reports does not work for datasets without criterion variable. See GMAT2 on TestAD.

**Comment by drabinova** [comment]
In Reports section: all is now prepared
In reports: Text and values from report options need to be added into reports, please check it out @JakHou 
Add also table with correlation between total scores and predictive criterion

**Comment by patriciamar** [comment]
Suggested wording for report
"Test for association between total score and criterion variable is based on Spearman`s ρ. The null hypothesis is that correlation is 0. Results: ρ=[...] (p-value [...]). Interpretation: The p-value is [less than] 0.05, thus we [reject] null hypothesis; total score and criterion variable [are positively correlated]."

[...] means interactive part.

**Comment by drabinova** [comment]
I mildly updated #320 , see in next commit. Please control and close.

**Comment by patriciamar** [comment]
Looks great.
Minor typos: please delete extra space behind "rho" in the first sentence and behind p-value in brackets.

**Comment by drabinova** [comment]
Typos fixed, see in next commit
