### ISSUE TITLE
Generalized DD plot

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#285]
Generalized version of difficulty/discrimination plot should be probably in Traditional item analysis sections and should be made in `ggplot2`

**Comment by LStepanek** [comment]
An idea: Let's consider refining and remaking a package (and an application, too) version of the function `DDplot()` in more general way -- there could be an extra argument, let's say `k` in the header of the function allowing us to choose a number of equal-size subsets which applicants' scores are split into. A default value of the argument `k` could be `k = 3`, i. e. there are three disjunct groups of applicants' scores and classic ULIs are plotted. The generalized version of difficulty/discrimination plot could then use the updated package version of `DDplot()` function (and probably run faster).

**Comment by drabinova** [comment]
Agree! Good idea 👍 I'll try edit the function soon. It won't be too complicated 😄

**Comment by drabinova** [comment]
Well, function for generalized discrimination could look like this:

```
gDiscrim <- function(x, k = 3, l = 1, u = 3){`
  if(u > k){
    stop("'u' need to be lower or equal to 'k'", call. = FALSE)
  }
  if(l > k){
    stop("'l' need to be lower than 'k'", call. = FALSE)
  }
  if(l <= 0){
    stop("'l' need to be greater than 0", call. = FALSE)
  }
  if(l >= u){
    stop("'l' should be lower than 'u'", call. = FALSE)
  }

  x <- na.exclude(as.matrix(x))
  n <- ncol(x)
  N <- nrow(x)

  ni <- as.integer(N/k)
  TOT <- apply(x, 1, sum)

  tmpx <- cbind(x, TOT)[order(TOT), ]

  tmpxU <- tmpx[as.integer((u - 1)*N/k + 1):as.integer(u*N/k), ]
  tmpxL <- tmpx[as.integer((l - 1)*N/k + 1):as.integer(l*N/k), ]

  Ui <- apply(tmpxU, 2, sum)
  Li <- apply(tmpxL, 2, sum)

  discrim <- (Ui - Li)/ni
  return(discrim[1:n])
}
```

This is generalized version of `discrim()` function from `psychometric` package:
```
# loading 100-item medical admission test data set
data(dataMedical)
x <- dataMedical[, 1:100]

# discrimination as in discrim() function from psychometric package
# compare to psychometric::discrim(x)
gDiscrim(x); psychometric::discrim(x)

# 5 groups, compare 4th and 5th
gDiscrim(x, k = 5, l = 4, u = 5)
```

Please, check it out. If it is correct, I'll send documented function into package as well as generalized version of `DDplot()` function.

**Comment by drabinova** [comment]
It is now in #301 pull request.

**Comment by drabinova** [comment]
This should be also resolved for reports - now the customized plot with the local application settings is plotted. There should be a choice.

**Comment by patriciamar** [comment]
In reports, in text above DDplot, description of discrimination should be more general or it needs to be reactive to take into account number of groups.

**Comment by drabinova** [comment]
It should be reactive. Maybe @LStepanek or @JakHou could look at it. There should be also an option in Reports page or at least some note about what is going to be printed

**Comment by drabinova** [comment]
I added sliders into Report page. Please add selected values into reports! Thanks

**Comment by patriciamar** [comment]
Suggested wording for interactive report:
"Difficulty (red) of items is estimated as percent of students who answered correctly to that item. Discrimination (blue) is by default described by difference of percent correct in upper and lower third of students (Upper-Lower Index, ULI); by rule of thumb it should not be lower than 0.2 (borderline in the plot), except for very easy or very difficult items. [In the current setting, the discrimination was customized (see also Martinkova, Stepanek, et al. (2017)) by changing number of groups and by changing which groups should be compared as follows: Displayed discrimination is a difference between the difficulty recorded in the [4-th] and [5-th] group out of total number of [5] groups.]"

[...] means interactive part. Last sentence is displayed only when the number of groups is not 3 or when other than 1st and 3rd groups are compared.

Also, "customize settings" still need to be activated for this part, customization of settings does not work for this part yet.

**Comment by drabinova** [comment]
Seems to work OK. Please control and close.

**Comment by patriciamar** [comment]
It seems that in reports (tested on html ), when using customize settings: number of groups 5, compare 4th and 5th, this option correctly described in the text, however, the plot remains with default settings (traditional ULI is displayed).

**Comment by drabinova** [comment]
Fixed. See in next commit

**Comment by patriciamar** [comment]
Checked, works! Howeer similar issue occurs with the distractor plots. Tested on GMAT, pdf, Customize settings - Distractors plots: number of groups = 5, plots remain with 3 categories.

**Comment by drabinova** [comment]
Fixed. Please control and close.

**Comment by patriciamar** [comment]
Seems to work well.
