### ISSUE TITLE
Loading Medical 100

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#287]
There are several errors when loading Medical 100 dataset. It works smoothly in shinyapps.io. Probably server bug.

**Comment by drabinova** [comment]
The bug is still there. Data page is now divided into two subpages. Data check was moved into 'Data exploration' subpage so changing of datasets doesn't take so long. However, exploration of Medical 100 dataset is still problematic. 

Tables in 'Data exploration' are now render by `DT::renderDataTable()` function. Change to `shiny::renderDataTable()` did not help. Change to `renderTable()` helped but it was possible only to display head of data. Again, rendering took quite a long time. We also tried just rendering the verbatim output, but the output was not really readable.

There is no bug in shinyapps.io nor in another mirror at Charles University.

**Comment by LStepanek** [comment]
In case of `renderTable()` rendering of datasets, why not to try a clause in terms of `head(DATASET_NAME, dim(DATASET_NAME)[1])` in order to display the whole dataset `DATASET_NAME`, supposing `head()` (not header?) does work as mentioned above?

Anyway, I believe there are some hidden issues in `ShinyItemAnalysis 1.2.0` version of the package since the ajax errors do not occur at other mirrors which use older version of the package (`ShinyItemAnalysis 1.1.5`); at least at Charles University mirror is still installed `1.1.5` version of the package.

**Comment by drabinova** [comment]
I don't follow what you mean by using `head(DATASET_NAME, dim(DATASET_NAME)[1])`, is that you want to print whole dataset? We use only the `head()`, i.e. first 6 rows, to avoid time consuming rendering of really large tables and moreover, when using classic `renderTable` these large tables are not really pretty. So these are the reasons of using `head(DATASET_NAME)` instead `DATASET_NAME` in code.

Probably you are right about hidden bug but we are not able to find it. I don't know what version of `ShinyItemAnalysis` package is now currently on shinyapps.io, maybe @patriciamar knows?

**Comment by LStepanek** [comment]
Well, just an idea and reply to "[...] Change to `renderTable()` helped but it was possible only to display head of data. [...]" where -- it sounds to me -- a displaying of only top six rows of each dataset is not presented as the desired result. Forget it. :)

**Comment by drabinova** [comment]
OIC what you mean! 😆  sorry for poor description

**Comment by patriciamar** [comment]
It seems version of ShinyItemAnalysis is not what is causing the difference. Since this morning, version 1.1.5 has been installed at CS server as well...

**Comment by drabinova** [comment]
The problem resists? Yes, I can see it now... 
This is kind of good new - that means that there is no syntax error in version 1.2.0!! Hurrah!! 
But it is also bad new - that means that there is a server bug and we don't know where.. So what will we do about that?

**Comment by patriciamar** [comment]
With server account, it may be possible to explore more the features of the server and possible reasons for this bug.

**Comment by patriciamar** [comment]
Bug is still present on shiny.cs.cas.cz server, when exploring the Medical100 dataset. When not exploring the dataset, analysis runs smoothly. The error message when using Data exploration is
"DataTables warning: table id=DataTables_Table_4 - Ajax error. For more information about this error, please see http://datatables.net/tn/7"

**Comment by drabinova** [comment]
With new server, it seems to work smoothly. Can we close this issue?

**Comment by patriciamar** [comment]
OK, closed now.
