### ISSUE TITLE
Add file names for downloaded plots

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#292]
Replace plot.png by file name describing the plot, e.g. figureHistogram.png, figureCorrPlot.png, figureScreePlot.png, figureDDplot.png, figureDistractorsItem001.png, etc.

**Comment by drabinova** [comment]
I'll do it soon. I'll also unify download button functions to be DB_plot-to-be-download.

**Comment by drabinova** [comment]
Well, I did this for first 3 pages - Summary, Validity, Item analysis.

Item validity is in #301. I'll send Summary and Validity in the next one.

**Comment by patriciamar** [comment]
Looks great! It seems that only plots in IRT and DIF sections need to be renamed now.

**Comment by drabinova** [comment]
Please control and close.

**Comment by patriciamar** [comment]
All seems correct, thanks!
