### ISSUE TITLE
Reports - Contents

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#307]
Contents should appear on the second page and should be updated as follows:

1. Summary  (remove "report")
2. Validity
- Correlation structure
- Predictive validity
3. Traditional item analysis  (remove "report")
- item analysis
- distractor analysis
4. IRT model
5. DIF/Fairness analysis (remove "report")
- Total scores by group
- Delta plot (remove "DIF detection")
- DIF detection using logistic regression
- DIF detection using ("u") multinomial regression
Session Info

We may consider adding section 2. Scoring above Validity, including standard scores from application

**Comment by drabinova** [comment]
Please control and close

**Comment by patriciamar** [comment]
Looks nice! Please change Standard scores to separate section with title Scoring. Please keep heading Summary table of standard scores: on separate line.

**Comment by drabinova** [comment]
See in next commit. Please control and close.

**Comment by patriciamar** [comment]
Checked, looks great.
