### ISSUE TITLE
New version of difNLR package

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#319]
In new version (v1.0.7) of `difNLR` package there are some changes that have to be handle in `ShinyItemAnalysis`:
* datasets `difMedical`, `difMedicaltest` and `difMedicalkey` were renamed to `MSATB`, `MSATBtest` and `MSATBkey`
* Item purification was implemented within functions `difNLR()` and `ddfMLR()`
* Purification option should be also added into reports for DDF
* Reference list can be updated

**Comment by drabinova** [comment]
See next commit. Please control and close.

**Comment by patriciamar** [comment]
Checked, seems to work well.
Option of item purification may be added to "Customize settings" of the reports in the future.

**Comment by drabinova** [comment]
It is already there
