### ISSUE TITLE
Corrplot - offer item clustering

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#327]
It would be great to offer clustering in Validity/Correlation structure. Similarly to McFarland et. al. www.lifescied.org/content/16/2/ar35.full.pdf+html?with-ds=yes
One or more clustering methods may be offered.
Pdf report should offer this feature as well.

**Comment by drabinova** [comment]
This is now implemented with Ward's method. Other methods will be implemented soon. It is also included in PDF and HTML reports.

**Comment by patriciamar** [comment]
Looks great! It would be nice to allow methods allowed in corrplot. Default would be none ("original" in corrplot function). Reordering should be done then also for number of clusters = 1 if some method is selected.

**Comment by drabinova** [comment]
Done in #341.
