### ISSUE TITLE
IRT training - include ability and horizontal+vertical lines

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#329]
For educational purposes, it may be helpful to include slider for "Latent ability" (default 0) and to print dotted horizontal and vertical lines associated with that latent ability on ICC curves. Interpretation may be added "For student with latent ability ... the probability of answering Item 1 correctly is ... (equation+numerical result) and probability of answering Item 2 correctly is ..."

**Comment by patriciamar** [comment]
Download button for plots would be helpful here in training session. It would be helpful if plots include parameter values as legend.

**Comment by drabinova** [comment]
Download buttons added. Now with legend.
Latent ability slider added. Horizontal and vertical lines added. Interpretation added.
Should I also add calculation of probability? 
See #334

**Comment by patriciamar** [comment]
Looks great! In figures, it may be nice to round all listed parameters to 1st decimal place.
It seems calculation (equation) is provided on the top of the page, maybe Equations can be moved below the Parameters and above Interpretation.

**Comment by drabinova** [comment]
Do you mean round numbers in plotly? I think this is not possible.  Equations were moved, see in next commit.

**Comment by patriciamar** [comment]
Looks great!
