### ISSUE TITLE
Data - confirmation

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#331]
On page Data, it would be great to obtain confirmation that data were sucessfully submitted (somewhere nearby Submit button). If a problem arises, we may say e.g. "Some error occured, check Data Exploration subsection to get idea what went wrong".

**Comment by drabinova** [comment]
Done in #333

**Comment by patriciamar** [comment]
Looks excellent!

Should we also provide some confirmation if practice dataset is changed?

**Comment by drabinova** [comment]
I think this is not necessary

**Comment by patriciamar** [comment]
OK, let's leave it as it is.
