### ISSUE TITLE
Kurtosis vs. Excess kurtosis

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#345]
In Summary, short explanation for Kurtosis, Skewness and other characteristics could be provided, including commenting on difference between kurtosis and excess kurtosis. This should also be incorporated into pdf-html report.

**Comment by drabinova** [comment]
I added some text. Please check it and then I'll add it also into reports.

**Comment by patriciamar** [comment]
Looks great!
