### ISSUE TITLE
Popis dat

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#35]
Je treba dodat obsahlejsi popis vzberu dat - chybi zminka, ze si uzivatel muze vybrat momentalne ze 3 datasetu z difNLR

**Comment by drabinova** [comment]
Přidáno, prosím o kontrolu

**Comment by patriciamar** [comment]
Vypada to pekne, pridala bych i na tuto stranku citaci Drabinova&Martinkova.

**Comment by drabinova** [comment]
Pridano
