### ISSUE TITLE
Plotting DIF ICCs

### ISSUE THREAD

**Issue by adelahladka** [patriciamar/ShinyItemAnalysis#356]
There are several issues when plotting ICCs in DIF/Fairness sections:
 - In Logistic and Logistic IRT Z the ICCs are based on results without any correction method. 
This is an issue of `difR` package and I do not see simple solution. The ideal approach is to change the function `difLogistic()`. The less ideal approach is to implement iterated weighted least squares into `difNLR` package and its `difNLR()` function for 2PL model.
 - In Lord IRT and Raju IRT only ICCs of larger models are displayed with no respect to DIF significance. Again, this is due to form of output of `difR` package. Possible solution is to estimate IRT models with e.g. `mirt` package.

**Comment by patriciamar** [comment]
This is now partly solved in v1.3.2 for DIF Logistic.

**Comment by patriciamar** [comment]
The issues regarding the correction methods are now solved. 
In Lord IRT and Raju IRT, the two curves are always plooted, this is due to modelling approach implemented in difR.
