### ISSUE TITLE
Page acceess count on shinyapps.io

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#375]
Any ideas how to make "Hits" count working properly on shinyapps.io?

**Comment by drabinova** [comment]
I think it is connected with this: https://shiny.rstudio.com/articles/share-data.html

**Comment by drabinova** [comment]
Something like following code need to be added into `server` for shinyapps.io

```
library(RAmazonS3)

counter <- getFile("rstudio-public", "counter.Rdata")

output$counter <- renderText({
  counter <- counter + 1
  addFile(I(counter), "rstudio-public", "counter.RData")
  paste0("Hits:", counter)
})
```
 However, package `RAmazonS3` cannot be currently installed. So the first option is not applicable.

I'll try to look at other options.
