### ISSUE TITLE
Loading group vector with missing values

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#389]
Loading data gives error message if missing values are present in group variable.
To overcome this issue, user currently needs to manually remove rows with missing group variable and upload data without these rows in the main dataset and omitting missing values in group vector.
In future this should be handled somehow inside the application.

**Comment by drabinova** [comment]
Part of #408. Please, check and close.

**Comment by patriciamar** [comment]
Looks good.
