### ISSUE TITLE
Cronbachovo alfa

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#4]
Přidat Cronbachovo alfa do Traditional Analysis/Item Analysis

**Comment by patriciamar** [comment]
Zakomponovat jeden z těchto příkazů do Traditional Item Analysis / Item Analysis nad tabulku.
psych::alpha(data) 
psychometric::alpha(data)

Případně také do Summary pod Summary Table.

**Comment by drabinova** [comment]
Přidáno
