### ISSUE TITLE
Error after excuting startShinyItemAnalysis()

### ISSUE THREAD

**Issue by huhsoleil** [patriciamar/ShinyItemAnalysis#455]
After installing and start the packages as below: 

install.packages("ShinyItemAnalysis")   
library(ShinyItemAnalysis) 
 startShinyItemAnalysis()

The error message appeared in the attached file. 
----------------
An error has occurred!
ui/uiValidity.R:194:13:  
Unexptected INCOMPLETE_STRING. 194: ('The following plot intelligibly depicts the criterion validity of every individual item (blue) together with its difficulty (red). 195: Items are ordered by difficulty. You can choose from two indices of criterion validity ^
------------------------------------
Is there any way to fix it?
Are there any packages to be installed for ShinyItemAnalysis? 

Thank you.
![error](https://user-images.githubusercontent.com/4025042/107592153-91d7fe80-6c4f-11eb-92d8-5aa6517701f0.JPG)

**Comment by patriciamar** [comment]
Whivh version of ShinyItemAnalysis package are you using? Please attach sessionInfo(). There were some updates recently, please download the most recent version 1.3.5 from CRAN and try again.

**Comment by huhsoleil** [comment]
p{margin-top:0;margin-bottom:0}
    


    Dear Sir/Madame,

Below is the sessionInfo().

[1] ShinyItemAnalysis_1.3.5

Does Korean language make a problem?

Thank you.

Best regards. 

Sun Huh
------------------------
sessionInfo()R version 4.0.3 (2020-10-10)Platform: x86_64-w64-mingw32/x64 (64-bit)Running under: Windows 10 x64 (build 19041)Matrix products: defaultlocale:[1] LC_COLLATE=Korean_Korea.949  LC_CTYPE=Korean_Korea.949   [3] LC_MONETARY=Korean_Korea.949 LC_NUMERIC=C                [5] LC_TIME=Korean_Korea.949    attached base packages:[1] stats     graphics  grDevices utils     datasets  methods   base     other attached packages:[1] ShinyItemAnalysis_1.3.5loaded via a namespace (and not attached): [1] tidyr_1.1.2           VGAM_1.1-5            splines_4.0.3         [4] tmvnsim_1.0-2         multilevel_2.6        shiny_1.6.0           [7] expm_0.999-6          statmod_1.4.35        stats4_4.0.3         [10] dcurver_0.9.2         pillar_1.4.7          lattice_0.20-41      [13] glue_1.4.2            digest_0.6.27         promises_1.1.1       [16] GPArotation_2014.11-1 minqa_1.2.4           colorspace_2.0-0     [19] cowplot_1.1.1         htmltools_0.5.1.1     httpuv_1.5.5         [22] Matrix_1.2-18         plyr_1.8.6            psych_2.0.12         [25] calculus_0.3.0        pkgconfig_2.0.3       deltaPlotR_1.6       [28] purrr_0.3.4           xtable_1.8-4          mvtnorm_1.1-1        [31] scales_1.1.1          CTT_2.3.3             later_1.1.0.1        [34] lme4_1.1-26           tibble_3.0.5          mgcv_1.8-33          [37] generics_0.1.0        ggplot2_3.3.3         ellipsis_0.3.1       [40] shinyjs_2.0.0         nnet_7.3-14           mnormt_2.0.2         [43] survival_3.2-7        magrittr_2.0.1        crayon_1.4.0         [46] mime_0.9              evaluate_0.14         msm_1.6.8            [49] nlme_3.1-149          MASS_7.3-53           ltm_1.1-1            [52] vegan_2.5-7           tools_4.0.3           lifecycle_0.2.0      [55] stringr_1.4.0         munsell_0.5.0         cluster_2.1.0        [58] mirt_1.33.2           Deriv_4.1.2           compiler_4.0.3       [61] tinytex_0.29          rlang_0.4.10          grid_4.0.3           [64] polycor_0.7-10        nloptr_1.2.2.2        rstudioapi_0.13      [67] difR_5.1              difNLR_1.3.7          rmarkdown_2.6        [70] boot_1.3-25           gtable_0.3.0          reshape2_1.4.4       [73] R6_2.5.0              knitr_1.31            psychometric_2.2     [76] dplyr_1.0.3           fastmap_1.1.0         permute_0.9-5        [79] stringi_1.5.3         parallel_4.0.3        Rcpp_1.0.6           [82] vctrs_0.3.6           tidyselect_1.1.0      xfun_0.20            > > 

------------ Original Message ------------ > From : patriciamar/ShinyItemAnalysis <reply@reply.github.com>> To : patriciamar/ShinyItemAnalysis <ShinyItemAnalysis@noreply.github.com>,> Cc : huhsoleil <shuh@hallym.ac.kr>,Author <author@noreply.github.com>> Sent : 2021-02-11 오후 6:12:49> Subject : Re: [patriciamar/ShinyItemAnalysis] Error after excuting startShinyItemAnalysis() (#455)

Which version of ShinyItemAnalysis package are you using? Please 
attach sessionInfo(). There were some updates recently, please download 
the most recent version 1.3.5 from CRAN and try again.
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.






Sun Huh
ORCID: http://orcid.org/0000-0002-8559-8640

**Comment by patriciamar** [comment]
Thanks. This should be now fixed with commit 063a1cb. Please try to install the newest version from GitHub using
devtools::install_github("patriciamar/ShinyItemAnalysis")
Please let us know if the issue persists.

**Comment by huhsoleil** [comment]
I succeeded in installing it.  It was fixed. Thank you.

**Comment by patriciamar** [comment]
Great!
