### ISSUE TITLE
After updating R to 4-0-4 recent version, ShinyItemAnalysis  does not work 

### ISSUE THREAD

**Issue by huhsoleil** [patriciamar/ShinyItemAnalysis#456]
After installing the recent R version, it does not work.

install.packages("ShinyItemAnalysis")
Installing package into ‘C:/Users/soleil/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/ShinyItemAnalysis_1.3.5.zip'을 시도합니다
Content type 'application/zip' length 2058359 bytes (2.0 MB)
downloaded 2.0 MB

package ‘ShinyItemAnalysis’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\soleil\AppData\Local\Temp\RtmponZgwg\downloaded_packages
> library(ShinyItemAnalysis)
This is ShinyItemAnalysis version 1.3.5
To run interactive shiny app, print startShinyItemAnalysis()
To learn more, visit www.ShinyItemAnalysis.org
> startShinyItemAnalysis()
----------------------------------------------------------------
ShinyItemAnalysis will start shortly as a background process.
The process automatically stops as you close the browser window.
----------------------------------------------------------------

-->However, no web version appeared.

If I install  as  > devtools::install_github("patriciamar/ShinyItemAnalysis")
There was an error message:

Package 'cachem' does not have name space.

Is there any ways to execute it appropriately? 

Thank you.

Sun

**Comment by patriciamar** [comment]
I am not able to reproduce the issue. Please try installing the newest (today's) version from GitHub. I recommend searching for error messages to find out how to proceed. The error message you specify above seems to be related to an external package.

**Comment by huhsoleil** [comment]
1.  I installed the package 'cachem' as follows: 

install.packages("cachem")
Installing package into ‘C:/Users/soleil/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version
  is later:
       binary source needs_compilation
cachem  1.0.3  1.0.4              TRUE

installing the source package ‘cachem’

URL 'https://cran.rstudio.com/src/contrib/cachem_1.0.4.tar.gz'을 시도합니다
Content type 'application/x-gzip' length 24493 bytes (23 KB)
downloaded 23 KB

ERROR: failed to lock directory 'C:/Users/soleil/Documents/R/win-library/4.0' for modifying
Try removing 'C:/Users/soleil/Documents/R/win-library/4.0/00LOCK-cachem'
Warning in install.packages :
  installation of package ‘cachem’ had non-zero exit status

2. I removed the directory  'C:/Users/soleil/Documents/R/win-library/4.0/00LOCK-cachem'
3. I installed the cachem package again.
4. After that,  I installed ShinyItemAnalysis 
devtools::install_github("patriciamar/ShinyItemAnalysis")   
library(ShinyItemAnalysi
startShinyItemAnalysis()
5.  Web version appeared. 
As you informed me, the problem is originated from the external package. 

Yesterday, I had a workshop of item analysis using ShinyItemAnalysis.  It was successful. I used the R code in  https://shiny.cs.cas.cz/ShinyItemAnalysis/.  Nine participants from Laos or Vietnam  finished the R coding for item analysis. 

Participants were happy running the ShinyItemAnalysis in R studdio. 

I appreciate you for the excellent package. 

I hope to use it again for the next workshop if requested. 

One request: Is there available code to convert the data of multiple choice response such as A, B, C, D to scored test with key (correct answer) in ShinyItemAnalysis or should I convert it by myself through script?

Sun

**Comment by patriciamar** [comment]
Thank you, we are glad to hear that!
Thanks for the suggestion, we can add to the Data section the sample R code for converting the multiple-choice data to scored test. One way to do it is using the key2binary() function from mirt package.
