### ISSUE TITLE
Total Scores and data

### ISSUE THREAD

**Issue by pukelevicius** [patriciamar/ShinyItemAnalysis#458]
Good day!
I am exploring ShinyItemAnalysis package with quite large test dataset, which consists of ordinal 40 items (questions) and 15k rows (participants).  First, I would like to know why in summary->standard scores the total score value is 20 max, because I know in my data participants can score more than 20 points. The second issue is with Traditional item analysis table which outputs me an error: "incompatible dimensions", how can I solve it? 
In general, I am interested in obtaining z_scores for each participant and question metrics, however I do not have luxury of obtaining group data and DIF matching variable vector. 
Thanks, Domantas

**Comment by patriciamar** [comment]
Hello,
which version of ShinyItemAnalysis are you using? Please try the newest GitHub version 1.3.5-1. Some issues with data loading appeared in version 1.3.5 and are now solved with the 1.3.5.-1 version.
No worries about group or DIF matching vector if you do not have them, those are not needed for the analyses you mentioned you are interested in.
Best, Patricia

**Comment by pukelevicius** [comment]
Thank you, Patricia, renewing version seems to solve my problems!

**Comment by patriciamar** [comment]
Thanks for the message, great!
