### ISSUE TITLE
Data is read incorrectly

### ISSUE THREAD

**Issue by pukelevicius** [patriciamar/ShinyItemAnalysis#459]
There is an issue when reading ordinal data. I have experienced that almost all rows have wrong  total scores and answers in general. For example when I open csv in excel or R I see that first correspondent got 1 point from 18th item, but in ShinyItemAnalysis the same cell's answer is 0. I tried looking into server Data.R script, but I couldn't figure out where is the problem.  Also, I am using newest app version from github.

**Comment by patriciamar** [comment]
Thanks for reporting. Data upload is often tricky. Check the following steps:
- You are using the latest version 1.3.6
- In Data upload you have specified Type "Ordinal" 
- On the bottom, you can see the following message: "Your data were successfully uploaded. Check the Data exploration tab."

If this is all true, in the Data / "Data exploration" tab you should be able to see correct values in the Main dataset. Note that ShinyItemAnalysis uses binarized data for some analyses and by default the binarization is defined by the maximal observed value in each item. In the "Data exploration" tab, this can be read under "Key" and "Scored Test".
 
If this does not help, you may send a sample data and we can take look at your specific case. Please be also more specific where do you see the discrepancy.

**Comment by pukelevicius** [comment]
I Do use the latest version and other steps are checked too. I observed displayed "Key" in data exploration tab and some questions have incorrect "cut-scores". Also, I have created a dataset of a vector with maximum scores for each question and I tried uploading it both as a "cut-score" and as a "maximal values". 

In a scenario when vector of maximum scores is uploaded as "maximal values" I get an error in "data exploration","Key (correct answers) / Cut-score" "Error: Can't assign 40 names to a 1 column data.table". Incorrect total scores are still present. 

While when vector of maximum scores is uploaded as "cut-scores" I have no error, but total scores are still incorrect. Regarding the binarization, I would like to know if it is possible to skip it as I imagine that with my ordinal data binarization is not needed, because some question in my data are worth e.g. 4 points (meaning that correspondent can score 1; 2 or 3 points on that same question).  So in case of binarization people who got points between maximum and minimum of that question will be accounted as scoring 0 points and further skill evaluation will be incorrect. So, uploading 'cut-scores' is probably not needed in my case.

**Comment by patriciamar** [comment]
The binarization is needed for some methods to run (e.g. Regression/logistic, IRT dichotomous, etc.). However, the total score should be taken from the original data, this is something that needs to be changed.
Meantime, if you could send a sample data to my e-mail, that would be helpful, I am not able to replicate the issues with cut-scores you are mentioning.

**Comment by patriciamar** [comment]
The total score calculation should now be fixed. Please check and close.
