### ISSUE TITLE
disconnections

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [patriciamar/ShinyItemAnalysis#461]
When I try to upload my data your program is disconnected

**Comment by patriciamar** [comment]
This is typically the case when your data is in wrong format. Please refer to our article in The R Journal (2018) https://doi.org/10.32614/RJ-2018-074 and examples of csv files provided in the supplementary material. When run locally in R, the error messages provide further hints on what is going on.

**Comment by NikitaKhromov-Borisov** [comment]
Thank you

вс, 27 июн. 2021 г. в 14:37, Patricia Martinkova ***@***.***>:
