### ISSUE TITLE
No issue, just an idea

### ISSUE THREAD

**Issue by AliciaFrancoMartinez** [patriciamar/ShinyItemAnalysis#463]
Hi, Patricia!

I am a young teacher of Psychometrics in Spain. I've just discovered your ShinyItemAnalysis tool and I am fascinated by it and its infinite didactic possibilities. 

I was wondering if you are interested in translating the tool to other languages. In my case, I'd be highly interested in translating it to Spanish for my students, do you think this would be possible?

Thank you in advance!
Alicia.

**Comment by patriciamar** [comment]
Hi Alicia,

Many thanks and I am glad ShinyItemAnalysis is being used and is of help! We are now working on SIAmodules, perhaps that would be the best platform for translated versions. Stay tuned!

Best wishes,
Patricia
