### ISSUE TITLE
Error on Table of estimated parameters on IRT

### ISSUE THREAD

**Issue by ngsg26** [patriciamar/ShinyItemAnalysis#464]
Hello, 
I've a dichotomous database with 269 entries in 15 collumns only with 0 and 1 (without missing values).
When i try to do an IRT analysis, there is an error on Table of estimated parameters and I can't figure out why.

**Comment by patriciamar** [comment]
Hello, 
Thanks for reporting. Please provide more information: 
Are you running ShinyItemAnalysis locally in your R session? If running locally, please provide your sessionInfo().
Or are you using one of the shiny servers? If so, on which link? Please retry on this mirror page to check if you have the same issue: https://cemp.shinyapps.io/ShinyItemAnalysis/
