### ISSUE TITLE
uncertain dependency on Matrix package

### ISSUE THREAD

**Issue by krkabol** [patriciamar/ShinyItemAnalysis#465]
Hello, 
when installing SIA on cca 10 students' laptops in class (i.e. random mix of several Windows-powered machines, installing everything from R/Studio to SIA for the first time), in two cases the app failed due a missing dependency of _Matrix_ package.

Solvable by explicit install `install.packages('Matrix')`, but the newbies were lost in the log output, please can you check the declared requirements?

thank you and good luck
Petr

**Comment by patriciamar** [comment]
This is most likely an error that affected all binaries for reverse LinkingTo of Matrix on certain CRAN mirrors: https://stat.ethz.ch/pipermail/r-package-devel/2023q4/010051.html
There is nothing we can do about it, but wait for the repository maintainers to rebuild manually or for the next binary build of lme4 (which seems to be the only affected dependency for ShinyItemAnalysis).
Thanks for reporting!
