### ISSUE TITLE
Uložení výstupů

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#6]
Promyslet a následně implementovat uložení obrázků/tabulek atd.

**Comment by patriciamar** [comment]
Ukladani histogramu funguje nyni pekne.
Prosim jeste ukladani ostatnich plotu. Preferovala bych jiny pomer stran, napr. 1:2 nebo 1:3, vetsina plotu by mela byt sirsi, jak je to v aplikaci.

**Comment by patriciamar** [comment]
Pozn. Z pridaneho kodu to vypada, ze by tam uz DownloadButtons mely byt, ale zobrazuji se pouze u histogramu.

**Comment by patriciamar** [comment]
Download Figure u DIF/Logistic IRT z hlasi Error "could not find function "plot_DIF_Logistic_IRT_ZInput".
U IRT plotu (Item characteristic curves, Item information curves, Test information curve) je mensi rozliseni nez jinde, prosim nastavit na vetsi. Test information curve stahuje omylem graf Item information curves.
