### ISSUE TITLE
Funkce

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#7]
Oddělit funkce do samostatného souboru a přidat dokumentaci. Nabídnout v rámci balíku ShinyItemAnalysis

**Comment by patriciamar** [comment]
Toto je důležité i pro zjednodušení poskytnutého zdrojového kódu.

**Comment by drabinova** [comment]
V nove verzi jsou jiz funkce v R slozce i s prvnim nastrelem dokumentace. Prosim o kontrolu a pripominky.

**Comment by patriciamar** [comment]
Pokud mozno, bylo by lepsi, aby funkce DDplot nepotrebovala promennou group, kterou nevyuziva. Obcas se take stava, ze nekdo do Shiny vlozi jen data odpovedi, bez vektoru skupiny. V description chybi na konci tecka.

**Comment by patriciamar** [comment]
Bylo by mozne do funkce plotDIFirt a plotDIFLogistic pridat Example?

**Comment by drabinova** [comment]
Vse hotovo
