### ISSUE TITLE
Download pdf

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#73]
Allow for quick export of test and item analysis (preferably to pdf).

Default setting: Summary, Traditional Analysis, for each item: Distractor plot, Multionmial logistic regression.  IRT section: 2PL IRT equation, plots, table. DIF section (if grouping parameter available): Total Scores, Delta plot, logistic table+plot of all DIF items.
(with possibility to check other options)

Deal with problem of possible long time response:
https://github.com/rstudio/shinyapps/issues/190
will most likely need some tuning: http://shiny.rstudio.com/articles/scaling-and-tuning.html

**Comment by patriciamar** [comment]
Vypada to skvele! Namety z brainstormingu:
- pagebreak between sections
- names of subsections (e.g. DIF Delta Plot, DIF Logistic)
- names of Tables and graphs when missing (IRT: Table: Parameter Estimates, DIF: Delta Plot) etc.
- table 1 remove collumn names
- one page for each item, smaller graphs
- IRT: which model (1PL, 2PL)
- IRT equation?
- DIF: histograms using gtable
- try option button (DIF?)

**Comment by drabinova** [comment]
Pokud se tiskne jen obrazek, je dobre do chunku pridat prikaz results="hide", to zpusobi, ze se napr nebudou ukazovat prvky listu, v kterem je graf ulozen (tj napr 
## 
## [[2]] 
u DIF logisticke regrese)

**Comment by drabinova** [comment]
Vypadá to skvěle! :) 

V dalším commitu přidám library(grid), která je momentálně vyžadována.
Pokud možno by to chtělo nastavit datum v anglickém formátu, nyní je česky.

**Comment by patriciamar** [comment]
Moc pěkné. Na úvod bude ještě dobré přidat informaci o aplikaci, např. This report was generated by ... version... see [odkaz].

**Comment by patriciamar** [comment]
Bude potřeba přidat potřebné balíky a software na Shiny server.

**Comment by patriciamar** [comment]
V současné chvíly reporty html na online verzi (Test) běží. 
Pro pdf report je jeste nutne na serveru nainstalovat novejsi verzi textu a chybejici baliky. 

Errors lze sledovat pomoci Putty na serveru v adresari /var/log/shiny-server. V putty se adesar meni pomoci prikazu cd /var/log... Cte se pomoci prikazu less (+ Tab na vybrani souboru posledniho logu).

**Comment by patriciamar** [comment]
Zda se, ze pdf reporty jiz na Testu take funguji, nutno odzkouset.

**Comment by patriciamar** [comment]
Report ma moc pekny novy vzhled! Libi se mi i obsah a intro.

Prosim jeste:
- Tuto uvodni informaci vlozit ihned pod datum (a odstranit z Introduction):
This Report was generated by ShinyItemAnalysis package version 1.0.0.
Copyright 2016 Patricia Martinkova, Adela Drabinova, Ondrej Leder and Jakub Houdek.
Supported by Czech Science Foundation under grant number GJ15-15856Y.
- Cast Introduction prejmenovat na Session Info
- Dale prosim o pridani korelacni struktury (za Summary prijde cast 2. Correlation structure, kam prijde pod sebe na jednu stranu corplot a scree plot)
- Cast IRT prosim nazvat IRT Report. Na zacatek prosim pridat Selected model: vypsat nazev a rovnici (poze toho zvoleneho). Prosim grafy ICC, IIC, TIC a Factor scores 2 pod sebe na jednu stranku, Tabulku az pod ne, prosim nazvat ji "Estimates of Item Parameters"
- V casti DIF prosim grafy 2 pod sebe na stranku, prosim take pridat cast DDF, opet s tiskem vystupu a s grafy signifikantne DDFovych polozek.

Jeste bych cast IRT predelala na mirt package, podari-li se jej zprovoznit i na serveru.

**Comment by patriciamar** [comment]
V nejnovejsi verzi nefunguje download. 1PL model hlasi:
ERROR: Perpendicular distances cannot be computed - one set of Delta scores is probably constant

Viz Test4

**Comment by drabinova** [comment]
Pro který data set? Já jsem to odzkoušela na všech 5 (včetně HCI).

Během zkoušení jsem narazila na problém, že nemáme ošetřenou skutečnost, že dataMedical 100 neobsahují vektor skupiny. Přidala jsem tedy ošetření, nyní se vypisuje chybová hláška. Pro tento dataset nebude možno ani vytvořit report. 

Nefunguje mi ale downoload PDF pro HCI. Nevím z jakého důvodu.

Své drobné úpravy brzy dodám

**Comment by patriciamar** [comment]
Nyní nemohu zkoušet, až večer. Pokud by šlo zařídit,  aby šlo generovat report i pro data bez vektoru group, bylo by to skvělé.

**Comment by drabinova** [comment]
Na to se bude muset podívat Jakub. Proč se pro HCI negeneruje report nevím, hlásí mi to:

```
Warning: Error in [: subscript out of bounds
Stack trace (innermost first):
    65: tapply
    64: data.frame
    63: plotDIFLogistic [C:/Users/Adisa/Documents/GitHub/ShinyItemAnalysis/R/plotDIFLogistic.R#93]
    62: <reactive:DIF_logistic_plotReport> [C:\Users\Adisa\Documents\GitHub\ShinyItemAnalysis\inst\shiny-examples\ShinyItemAnalysis/server.R#2985]
    51: DIF_logistic_plotReport
    50: download$func [C:\Users\Adisa\Documents\GitHub\ShinyItemAnalysis\inst\shiny-examples\ShinyItemAnalysis/server.R#3734]
     1: runApp
Error : subscript out of bounds
```

Takže to vypadá, že je problém s vykreslováním plotDIFlogistic. Koukala jsem se na kód a jedná se o tuto část:

```
  hv_R <- data.frame(X1 = as.numeric(levels(as.factor(score_R))),
                     X2 = tapply(data[group == 0, item], as.factor(score_R), mean))
```
Možná to ale souvisí s tím, že v tomto datasetu nemáme žádnou DIFovou položku a report neví, co vypsat.

**Comment by JakHou** [comment]
**Reporty i bez vektoru group**

Problém s generováním spočívá asi v tom, že veškeré ověřování existence vektoru group funguje tak, že pokud vektor je, je vše v pořádku, pokud ne, tak se vyhodí error. To znamená, že jakýkoliv dotaz (byť jen na pouhou existenci vektoru) vyhodí chybovou hlášku a celý proces se zastaví, tudíž není možné vygenerovat report. 

Pokud by tedy bylo možné nějak předělat validování vektoru group, bylo by to skvělé. Pokud by to možné nebylo nebo pokud by to bylo až příliš pracné, tak zkusím vymyslet jiný způsob podmiňování generovaného obsahu

**Comment by drabinova** [comment]
**Reporty bez group**
Dosud to bylo ale stejné, error tam byl vždy, když chyběla group, respektive group byla nesmyslná nebo měla špatné rozměry. Teď akorát se místo podivných výstupů vypisuje konkrétní hláška.

Upřímně nevím, jak tyto errory ošetřit. validation() působí, že se dále nic neprovádí a vyhodí ERROR. [**Tady**](http://stackoverflow.com/questions/34422342/show-warning-to-user-in-shiny-in-r) řeší jak v shiny nastavit WARNING, ale bohužel teď nemám čas se na to dívat podrobněji nebo to implementovat.

**Report pro HCI**
Tady ovšem group nechybí, takže nevím, kde je problém

**Comment by patriciamar** [comment]
Moc diky za pripravu podmineneho generovani!
Nejnovejsi verze je na Test4, testuji ji take lokalne.

Lokalne mi to hlasi chybu (zkousim GMAT data, 1PL, html nebo pdf): ERROR: pandoc document conversion failed with error 43. Poradite mi, kde muze byt problem?

Na serveru (Test4) se mi to zatim take nepodarilo vygenerovat.

**Comment by drabinova** [comment]
Lokálně nemám s generováním reportů žádný problém.  Funguje obojí - html i pdf. Test4 server mi hlásí **Reason: Error reading from remote server**
Není tam nahrána nějaká špatná verze?

**Comment by patriciamar** [comment]
Lokálně: html zdá se generuje. Problém je u pdf, kde mi to hlásí (v R):
Error in : pandoc document conversion failed with error 43
Může mi lokálně chybět nějaká knihovna?

Na serveru mám také stejný error. Verze by měly být správné.

**Comment by JakHou** [comment]
Na serveru dostávám 502 proxy error. Pokud ale kliknu na přiložený odkaz, který error poskytuje, report se vygeneruje. 

Dle session info z reportu je na serveru minimálně neaktualizovaný balík Shiny. 

Odkazovaný problém z balíku Rmarkdown by neměl být problémem v tomto případě, neboť se v reportu neobjevuje nikde žádné číslo, které by bylo generováno uprostřed textu. Jedině v abstract u verze balíku ShinyItemAnalysis, to bych ale řekl, že je spíše string než číslo.

**Comment by drabinova** [comment]
Dobré je také si lokálně aktualizovat všechny balíčky a znovu zkusit generování reportu. To by mohlo odhalit, zda problém není právě zde. 

Na test4 mám také 502 proxy error jako Jakub

**Comment by JakHou** [comment]
Právě jsem dostal 502 proxy error i i jen při nahrávání testu4. Řrekl bych, že možná půjde o nějaký sítový/serverový problém. Nebo bug.

**Comment by drabinova** [comment]
Taky se mi to stalo, není náš problém čas načítání? Viz [**např. toto**](http://serverfault.com/questions/185894/proxy-error-502-reason-error-reading-from-remote-server-with-apache-2-2-3-de)

**Comment by drabinova** [comment]
Co je napsáno v logu serveru?

**Comment by patriciamar** [comment]
Jakube, log serveru je k nalezeni po prepnuti do adresare
cd /var/log/shiny/server
ls
less ShinyItemAnalysisTest4        [+tab, ten doplni zbytek nazvu souboru]

Pridame prava i Adele, at muze take kontrolovat.

Vidim tam errory s presunem vygenerovanych pdf obrazku do tmp adresare. Tento problem jsme uz v minulosti meli, ale reporty se ve finale generovaly. Jiny error tam neni.

Problem s casem by byt mohl, takze osetreni, aby to nespadlo, kdyz to trva dele, by bylo prima.

**Comment by patriciamar** [comment]
Jakube, opravdu to generuje po kliknuti na odkaz vygenerovany Errorem, ale prekvapuje mne, ze to generuje report starsi verze, pritom v adresari Test4 je nahrana ta nejnovejsi.

Pokud mozno, prosim zkuste nahrat nejnovejsi soubory na server do Test a otestovat vcetne nahlednuti na Errory v logu serveru (bude to pak soubor ShinyItemAnalysisTest... nikoliv Test4).

**Comment by patriciamar** [comment]
Pro data GMAT mi nyni html generovani 1PL hlasi chybu "ERROR: render params not declared in YAML: corr_plotscree_plotisGroupPresentmodel_DDF_printplot_DDFReportInput"

Soucasne to negeneruje corrplot v aplikaci. Zazracne to generuje corrplot v pdf reportu.

**Comment by patriciamar** [comment]
Pro data perle hlasi reporty chybu "ERROR: A continuous variable can not be mapped to linetype", zda se, ze je problem s formatem nactenych dat. V budoucnu budeme chtit, aby aplikace umela analyzvat i ordinalni data. Prozatim by mohlo stacit udelat z dat vzdy na zacatku character/factor(?)

**Comment by patriciamar** [comment]
Mozna predelani reportu na MIRT zrychli generovani a vyresi stavajici Errory.

**Comment by drabinova** [comment]
Chyby pro Perle by mely byt odstraneny. Nyni by mela aplikace zvladnout i skorovana data. Vsechny reporty slo lokalne vygenerovat.

**Comment by patriciamar** [comment]
Reporty se podarilo vygenerovat na serveru na TestAD i pro data Perle, diky!
Dokonce html i pdf probehly oba bez chybove hlasky! (mozna uz spravce opravil ukladani?)
V reportech chybi grafy IIC, ICC a TIC pro IRT model. (neni to opet nejaka starsi verze?)

**Comment by drabinova** [comment]
Lokálně mi jdou generovat pdf i html reporty. Obsahuji oba vsechny krivky pro IRT. Asi starsi verze. Opravila jsem ted drobny prepis pro Rasch model v generovani reportu. Snad uz ok!

**Comment by patriciamar** [comment]
Testuji, nejnovejsi verze je opet na TestAD. html report se vygeneroval napotreti, PDF ihned, oba vypadaji dobre!
Zda se, ze to opet v aplikaci negeneruje tabulku Model comparison, ktera uz drive fungovala. Nepouzila se nejaka starsi verze souboru, kdyz se neco prepisovalo?

**Comment by drabinova** [comment]
Tabulka je snad vyresena

**Comment by patriciamar** [comment]
Na serveru by mely byt nejnovejsi soubory. Download button jiz funguje. Reports mi obe hlasi pri defaultnim 1PL modelu ERROR: 'data' must be of a vector type, was 'NULL'

**Comment by drabinova** [comment]
Lokálně mi to hází u jakéhokoliv IRT modelu:
`Warning: Error in knit_params_get: render params not declared in YAML: wrightMap`

**Comment by JakHou** [comment]
> Lokálně mi to hází u jakéhokoliv IRT modelu:
> Warning: Error in knit_params_get: render params not declared in YAML: wrightMap

Problém je v reportech, stačí v hlavičce dopsat "wrightMap: NA", lokálně to ale deklarované mám.  Určitě jsem to nechával i v commitech. Na gitu, jak se dívám, to změněné není

**Comment by JakHou** [comment]
Tak teď mi to doslova zmizlo před očima v lokálních souborech

**Comment by patriciamar** [comment]
Diky za Wright Map, zda se, ze to dobre funguje!

**Comment by patriciamar** [comment]
Pretrvava pouze problem s downloadem, vetsinou napoprve nestahne. Zalozila bych to jako novy anglicky Issue s tim, ze po kliknuti na link se to vetsinou napodruhe nebo napotreti stahne. Doporucila bych, aby pouzivali lokalne (i kdyz tam je zas potreba mit pro pdf report nainstalovany TeX..)
Takze uzavreme?
