### ISSUE TITLE
Add corrplot / correlation structure

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#76]
Consider adding a corplot or other measures of correlaton structure under Summary/Correlation Structure.

Code:
library(psych)
library(corrplot)
corP <- polychoric(data)
corrplot(corP$rho)
round(corP$rho,2)

Download plot/matrix

**Comment by patriciamar** [comment]
Pod to take scree plot (eigen values):

plot(1:length(eigen(corP$rho)$values),eigen(corP$rho)$values, ylab="eigen value")
lines(1:length(eigen(corP$rho)$values),eigen(corP$rho)$values)

print values: 
round(eigen(corP$rho)$values,3) 

Viz take pomoci ggplotu:
https://sakaluk.wordpress.com/2016/05/26/11-make-it-pretty-scree-plots-and-parallel-analysis-using-psych-and-ggplot2/

**Comment by drabinova** [comment]
Pridana zakladni verze. Asi by bylo dobre pridat i nejake popisky atd. Novou verzi scree plotu pripravim.

**Comment by drabinova** [comment]
Pridana verze pomoci ggplot2 a take popisky
