### ISSUE TITLE
Slidery

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#83]
Vypadá to, že slidery pro MH mají jinou strukturu v kódu než pro ostatní DIF metody. Bylo by dobré to v kódu sjednotit. Viz řádky kolem cca 350 v server.R.

**Comment by drabinova** [comment]
U DDF se mi stává (obdobně jako jsme viděli posledně u DIFu), že slider začne přeskakovat z položky na položku a zpět

**Comment by drabinova** [comment]
Teď už to vypadá OK! 
Ještě jedna malá drobnost - v Items slideru mám stupnici 1-3-5-7-9-12-atd, je to tak schválně, že najednou se po 9 přepneme do sudých čísel? Slider pak úplně přesně neodpovídá stupnici, např. pro 12 je spíš těsně za 12 atd. Navíc mezi ostatními čísly jsou dvě čárky, přitom je tam ale jen jedna hodnota (krom teda 9-12)
Toto se děje u všech item slideru krom MH. U MH je rozpětí pro Items jen 1-10!

**Comment by JakHou** [comment]
O problému s podivným číslováním vím. Bohužel ale nemám tušení, proč se tak děje. (Možná nějaký vnitřní problém s updatem a javascriptem? ) 

MH slider opraven, děkuji za upozornění

**Comment by drabinova** [comment]
Ok, ono se stejně jedná o celkem nepodstatnou věc. Předám to do issue "Různá vylepšení". Díky za opravu MH :) Tuhle část tedy uzavírám
