### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#86]
Bylo by dobre zjistit, ktere balicky vyuzivaji ktere funkce. Jelikoz se nam seznam pouzitych balicku dost rozsiruje, stava se pri kompilovani balicku, ze dochazi ke kolizim v jmenech funkci. Napr existuje objekt alpha v ggplot2 a take funkce alpha v balicku psych. Pokud budeme vedet, ktere funkce nase aplikace vyuziva, lze to pak jednoduse specifikovat, co se ma natahnout a nebude dochazet k temto problemum, ktere mimo jine brani v publikovani na CRANu

**Comment by drabinova** [comment]
Momentalne je hlavnim problemem:
factor.scores v baliccich ltm a psych
alpha v ggplot2 a psych
%+% v ggplot2 a psych
polyserial v CTT a psych

Tedy by momentalne stacilo zjistit, ktere funkce z balicku psych pouzivame.

**Comment by JakHou** [comment]
Našel jsem tuhle funkci z balíku NCmisc. Nedaří se mi ji však použít. 

https://rdrr.io/cran/NCmisc/man/list.functions.in.file.html

**Comment by patriciamar** [comment]
Z psych myslím používáme pouze funkce alpha a teď nově tetrachorickou korelaci pro corrplot.

Lze zkusit tahat z psych jen konkrétně tyto dvě funkce a zjistit,  zda to hlásí chybu (a případně jakou - co mu chybí).

**Comment by drabinova** [comment]
Taky mi to nefungovalo, tak jsem trochu upravila kod:

tmp <- getParseData(parse("server.R", keep.source = T))
tmp <- tmp[tmp$token == "SYMBOL_FUNCTION_CALL", ]

tmp <- unique(if (alphabetic) {
  sort(tmp$text)
}
else {
  tmp$text
})

src <- paste(as.vector(sapply(tmp, find)))
outlist <- tapply(tmp, factor(src), c)

print(outlist)


a uz mi to neco ukazuje :) Clovek akorat musi mit nahrane vsechny potrebne balicky, aby se to zvladlo roztridit. Takze ted uz to bude snadnejsi odhalit, kde je problem. Diky za pomoc! Kouknu na to mezi svatky

**Comment by drabinova** [comment]
Castecne je to vyreseno. Jeste zbyva osetrit objekt alpha, ktery pouzivame v ramci dvou balicku - ggplot2 a psych

**Comment by drabinova** [comment]
Vyreseno
