### ISSUE TITLE
Různá vylepšení - k diskuzi

### ISSUE THREAD

**Issue by drabinova** [patriciamar/ShinyItemAnalysis#95]
Zakládám nové vlákno, kde můžeme navrhovat drobná zlepšení.

- Zvážit, zda neodstranit odkazy na staré verze z dolního panelu. Ponechala bych je pouze v About sekci.
**HOTOVO, na jednom řádku**

- Nebylo by lepší začínat na záložce Data? Kdykoliv o tom mluvíme, vždy se začíná představením datových souborů
**HOTOVO**

- Je možno odstranit zakomentovaný kód? Nevím, jestli jej budeme ještě potřebovat?
**HOTOVO**

- v Items slideru je stupnice 1-3-5-7-9-12 atd., tedy mezi 9 a 12 jsou dvě čísla místo jednoho. Slider pak úplně přesně neodpovídá stupnici, např. pro 12 je spíš těsně za 12 atd. Navíc mezi ostatními čísly jsou dvě čárky, přitom je tam ale jen jedna hodnota (krom teda 9-12)

- momentálně úplně chybí jakékoliv upozornění na chybějící group a tedy nemožnost spustit DIF analyzu
**Přidáno statické upozornění aspoň do DATA sekce**

- Rozšířit popisky datasetů v DATA sekci
**HOTOVO**

- Zvážit přidání záložky HOME resp upravit záložku ABOUT, kde by byl popisek a úvod k ShinyItemAnalysis. Zatím je popisek ponechán v Summary/Total scores
**Návrh viz pull request 104 - ABOUT section**

- Zvážit přidání comment section

- Zvážit používání google analytics, abychom věděli, co uživatelé používají

- U Summary/Standard Scores chybí jakýkoliv popisek
**PŘIDÁNO**

- Připadá mi, že Correlation Structure se spíš hodí pod Traditional Analysis než Summary. V Summary jsou pouze statistiky ohledně skórů, kdežto v Trad. An. jsou položky. Corr. Str. se týká ovšem korelací mezi položkami a se skóry (myslím) nepracuje
**Zatím přemístěno**, **Nyní na konci TA**

- Nebylo by dobré do nadpisu přidat název aplikace?
**Momentálně přidáno**

**Comment by patriciamar** [comment]
Odkazy na starší verze je nutné ponechat,  lze je ale dát na jeden řádek / zkrátit. List Data lze dát jako první. Krásně to roste!

**Comment by patriciamar** [comment]
Vylepšení vypadají moc pěkně.
